import { Chapter, QuestionType } from './types';

export const chapters: Chapter[] = [
  {
    id: 'intro',
    title: '导言',
    questions: [
      { id: 'i-s-1', type: QuestionType.Single, question: '中国新民主主义革命的伟大开端是（ ）。', options: ['A.鸦片战争', 'B.辛亥革命', 'C.新文化运动', 'D.五四运动'], answer: ['D'] },
      { id: 'i-s-2', type: QuestionType.Single, question: '中国共产党团结带领中国人民进行的一切奋斗、一切牺牲、一切创造，归结起来就是一个主题，即（ ）。', options: ['A.推翻封建专制统治', 'B.建立人民民主专政的新中国', 'C.实现中华民族伟大复兴', 'D.实现共同富裕'], answer: ['C'] },
      { id: 'i-s-3', type: QuestionType.Single, question: '学习中国近现代史，需要牢固树立唯物史观，警惕和反对（ ）。', options: ['A.历史虚无主义', 'B.唯心主义', 'C.唯物主义', 'D.形而上学'], answer: ['A'] },
      { id: 'i-s-4', type: QuestionType.Single, question: '中国近代史上第一个不平等条约是（ ）。', options: ['A.《南京条约》', 'B.《尼布楚条约》', 'C.《虎门条约》', 'D.《穿鼻条约》'], answer: ['A'] },
      { id: 'i-s-5', type: QuestionType.Single, question: '1844年7月，清政府被迫与美国签订了不平等条约( )', options: ['A.《虎门条约》', 'B.《望厦条约》', 'C.《黄埔条约》', 'D.《爱珲条约》'], answer: ['B'] },
      { id: 'i-s-6', type: QuestionType.Single, question: '近代中国的社会性质是（ ）。', options: ['A.封建社会', 'B.殖民地社会', 'C.资本主义社会', 'D.半殖民地半封建社会'], answer: ['D'] },
      { id: 'i-s-7', type: QuestionType.Single, question: '近代中国，要争得民族独立和人民解放，必须首先（ ）。', options: ['A.发展教育', 'B.发展工业', 'C.改革经济', 'D.进行反帝反封建的民主革命'], answer: ['D'] }
    ]
  },
  {
    id: 'ch1',
    title: '第一章 进入近代后中华民族的磨难与抗争',
    questions: [
      // 单选题 (34道)
      { id: 'c1-s-1', type: QuestionType.Single, question: '中国封建社会的文化思想体系以 ( )为核心。', options: ['A.佛教', 'B.道家思想', 'C.法家思想', 'D.儒家思想'], answer: ['D'] },
      { id: 'c1-s-2', type: QuestionType.Single, question: '中国封建社会政治的基本特征是（ ）。', options: ['A.宗族家长制', 'B.宗法等级制度', 'C.封建君主专制制度', 'D.王朝更迭'], answer: ['C'] },
      { id: 'c1-s-3', type: QuestionType.Single, question: '中国封建社会社会结构的特点是族权和政权相结合的封建宗法等级制度。其核心是（ ）。', options: ['A.儒家思想', 'B.君主专制制度', 'C.宗族家长制', 'D.“三纲五常”'], answer: ['C'] },
      { id: 'c1-s-4', type: QuestionType.Single, question: '中国封建社会后期出现的“盛世”是( )。', options: ['A.文景之治', 'B.贞观之治', 'C.开元之治', 'D.康乾盛世'], answer: ['D'] },
      { id: 'c1-s-5', type: QuestionType.Single, question: '1640 年( )标志着世界历史开始进入资本主义时代。', options: ['A.美国独立战争', 'B.法国大革命', 'C.英国资产阶级革命', 'D.俄国十月革命'], answer: ['C'] },
      { id: 'c1-s-6', type: QuestionType.Single, question: '在 19 世纪中叶，被称为“海上霸王”、“日不落”帝国的殖民国家是( )', options: ['A.美国', 'B.德国', 'C.日本', 'D.英国'], answer: ['D'] },
      { id: 'c1-s-7', type: QuestionType.Single, question: '1842 年英国强迫清政府签订《南京条约》，把( )割让给英国。', options: ['A.香港岛', 'B.台湾岛', 'C.九龙半岛', 'D.澎湖列岛'], answer: ['A'] },
      { id: 'c1-s-8', type: QuestionType.Single, question: '1895 年日本强迫清政府签订( )，割去中国台湾全岛及所有附属岛屿和澎湖列岛。', options: ['A.《辛丑条约》', 'B.《马关条约》', 'C.《北京条约》', 'D.《望厦条约》'], answer: ['B'] },
      { id: 'c1-s-9', type: QuestionType.Single, question: '19 世纪末，帝国主义瓜分中国，划分势力范围。日本也声明把（ ）作为其势力范围。', options: ['A.台湾', 'B.东三省', 'C.福建', 'D.山东'], answer: ['C'] },
      { id: 'c1-s-10', type: QuestionType.Single, question: '根据（ ）规定，帝国主义列强获得了在中国驻兵的特权。', options: ['A.《辛丑条约》', 'B.《马关条约》', 'C.《北京条约》', 'D.《天津条约》'], answer: ['A'] },
      { id: 'c1-s-11', type: QuestionType.Single, question: '第二次鸦片战争中，（ ）放火烧了圆明园的侵略军。', options: ['A.英军', 'B.英法联军', 'C.日军', 'D.八国联军'], answer: ['B'] },
      { id: 'c1-s-12', type: QuestionType.Single, question: '允许外国公使常驻北京，始于（ ）规定。', options: ['A.《南京条约》', 'B.《马关条约》', 'C.《北京条约》', 'D.《天津条约》'], answer: ['D'] },
      { id: 'c1-s-13', type: QuestionType.Single, question: '英国人赫德自1863年任总税务司开始，掌握中国海关大权达40余年之久。他曾向清政府提岀（ ），教训中国政府必须遵守不平等条约。', options: ['A.《烟台条约》', 'B.《局外旁观论》', 'C.《五口通商章程》', 'D.子口税'], answer: ['B'] },
      { id: 'c1-s-14', type: QuestionType.Single, question: '两次鸦片战争后，中国一共开放了（ ）通商口岸。', options: ['A. 5个', 'B. 10个', 'C.15个', 'D.16个'], answer: ['D'] },
      { id: 'c1-s-15', type: QuestionType.Single, question: '中国近代史上，帝国主义通过侵略战争，勒索巨额赔偿，公开掠夺中国。索赔最高的一次是（ ），本息合计高达10亿两。', options: ['A.甲午战争', 'B.抗日战争', 'C.八国联军侵华战争', 'D.鸦片战争'], answer: ['C'] },
      { id: 'c1-s-16', type: QuestionType.Single, question: '属于《马关条约》内容的是（ ）。', options: ['A. 允许外国公使驻京', 'B.允许外国传教士在中国传教', 'C. 允许外国人在中国办工厂', 'D.允许外国人建立租界'], answer: ['C'] },
      { id: 'c1-s-17', type: QuestionType.Single, question: '中国近代史上，（ ）是中国人民第一次大规模的反侵略武装斗争。', options: ['A.三元里人民的抗英斗争', 'B. 太平天国运动', 'C. 义和团运动', 'D.抗日战争'], answer: ['A'] },
      { id: 'c1-s-18', type: QuestionType.Single, question: '中法战争镇南关大捷中率部英勇杀敌的将军是( )。', options: ['A.冯子材', 'B.关天培', 'C.丁汝昌', 'D.刘永福'], answer: ['A'] },
      { id: 'c1-s-19', type: QuestionType.Single, question: '中法战争期间，法舰进犯台湾被（ ）指挥守军击退。', options: ['A.刘永福', 'B.徐骧', 'C.刘铭传', 'D.冯子材'], answer: ['C'] },
      { id: 'c1-s-20', type: QuestionType.Single, question: '帝国主义瓜分中国图谋破产的根本原因是( )。', options: ['A.列强之间的矛盾和相互制约', 'B.中国人民的反侵略斗争', 'C.帝国主义国家中正义力量的干涉', 'D.中国自给自足的经济社会结构'], answer: ['B'] },
      { id: 'c1-s-21', type: QuestionType.Single, question: '中国近代历次反侵略战争失败的原因中更根本的原因是( )。', options: ['A.帝国主义列强的优异的社会制度', 'B.帝国主义列强的强大的经济、军事实力', 'C.中国落后的军事力量', 'D.中国社会制度的腐败'], answer: ['D'] },
      { id: 'c1-s-22', type: QuestionType.Single, question: '（ ）是近代中国睁眼看世界的第一人。', options: ['A.林则徐', 'B.魏源', 'C.郭嵩焘', 'D.郑观应'], answer: ['A'] },
      { id: 'c1-s-23', type: QuestionType.Single, question: '（ ）在 1843 年编成《海国图志》一书。', options: ['A.林则徐', 'B.魏源', 'C.马建中', 'D.郑观应'], answer: ['B'] },
      { id: 'c1-s-24', type: QuestionType.Single, question: '近代中国，（ ）提出了“师夷长技以制夷”的思想。', options: ['A.林则徐', 'B.魏源', 'C.龚自珍', 'D.李鸿章'], answer: ['B'] },
      { id: 'c1-s-25', type: QuestionType.Single, question: '中国近代史上（ ）最早喊出“救亡”的口号。', options: ['A.严复', 'B.康有为', 'C.林则徐', 'D.孙中山'], answer: ['A'] },
      { id: 'c1-s-26', type: QuestionType.Single, question: '近代中国，（ ）最早喊出“振兴中华”的时代最强音。', options: ['A.严复', 'B.康有为', 'C.林则徐', 'D.孙中山'], answer: ['D'] },
      { id: 'c1-s-27', type: QuestionType.Single, question: '1843 年，魏源编成《海国图志》，书中“师夷长技以制夷”所说的“长技”主要是指西方的（ ）。', options: ['A.宗教和思想文化', 'B.教育和人才培养', 'C.军事和科学技术', 'D.民主和政治制度'], answer: ['C'] },
      { id: 'c1-s-28', type: QuestionType.Single, question: '帝国主义侵略中国的最终目的是要瓜分中国、灭亡中国。1895年中国在甲午战争中战败后，列强掀起了瓜分中国的狂潮，这集中表现在（ ）。', options: ['A．设立完全由外国人直接控制和统治的租界', 'B．竞相租借港湾和划分势力范围', 'C．外国资本在中国近代工业中争夺垄断地位', 'D．从侵占中国周边邻国发展到蚕食中国边疆地区'], answer: ['B'] },
      { id: 'c1-s-29', type: QuestionType.Single, question: '1840 年鸦片战争以后，中华民族面临生死存亡的形势日益严峻，促使中国人民的民族意识开始普遍觉醒的重大事件是（ ）。', options: ['A.日本全面侵华战争', 'B.中日甲午战争', 'C.八国联军侵华战争', 'D.中法战争'], answer: ['B'] },
      { id: 'c1-s-30', type: QuestionType.Single, question: '近代中国诞生的新兴的被压迫阶级是工人阶级。中国工人阶级最早出现于( ) 。', options: ['A.19 世纪40至50年代', 'B.19 世纪60年代', 'C.19 世纪70年代', 'D.19 世纪80年代'], answer: ['A'] },
      { id: 'c1-s-31', type: QuestionType.Single, question: '近代中国最革命的阶级是( )。', options: ['A.工人阶级', 'B.民族资产阶级', 'C.农民阶级', 'D.小资产阶级'], answer: ['A'] },
      { id: 'c1-s-32', type: QuestionType.Single, question: '近代中国革命的主力军是（ ）。', options: ['A.农民阶级', 'B.工人阶级', 'C.买办资产阶级', 'D.民族资产阶级'], answer: ['A'] },
      { id: 'c1-s-33', type: QuestionType.Single, question: '十九世纪末资本主义进入帝国主义阶段后，( )成为殖民主义剥削的重要形式，并出现瓜分世界的狂潮。', options: ['A.掠夺土地', 'B.贩卖奴隶', 'C.商品输出', 'D.资本输出'], answer: ['D'] },
      { id: 'c1-s-34', type: QuestionType.Single, question: '鸦片战争后，中国经济逐渐被卷入世界资本主义市场，其对中国的影响不包括( )', options: ['A.封建地主土地所有制瓦解', 'B.自给自足的自然经济逐步解体', 'C.中国资本主义的产生和发展', 'D.英国对华商品输出激增'], answer: ['A'] },

      // 多选题 (27道)
      { id: 'c1-m-1', type: QuestionType.Multiple, question: '中国近代从1840年鸦片战争以来，资本-帝国主义列强发动了（ ）。', options: ['A.鸦片战争', 'B.第二次鸦片战争', 'C.中日甲午战争', 'D.八国联军侵华战争'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-2', type: QuestionType.Multiple, question: '中英《南京条约》签订后，美、法趁火打劫，相继逼迫清政府签订的不平等条约有（ ）。', options: ['A.《虎门条约》', 'B.《望厦条约》', 'C.《黄埔条约》', 'D.《天津条约》'], answer: ['B', 'C'] },
      { id: 'c1-m-3', type: QuestionType.Multiple, question: '中国近代史上，帝国主义侵华战争中，屠杀中国人，制造了（ ）。', options: ['A.旅顺惨案', 'B.海兰泡惨案', 'C.江东六十四屯惨案', 'D.南京大屠杀'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-4', type: QuestionType.Multiple, question: '下列条约中涉及香港问题的有（ ）。', options: ['A.《南京条约》', 'B.《辛丑条约》', 'C.《北京条约》', 'D.《黄埔条约》'], answer: ['A', 'C'] },
      { id: 'c1-m-5', type: QuestionType.Multiple, question: '从 1858 年到1881年，俄国先后迫使中国签订了( )，侵吞了我国北方150多万平方公里的领土。', options: ['A.《瑷珲条约》', 'B.《北京条约》', 'C.《勘分西北界约记》', 'D.《改订伊犁条约》及勘界议定书'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-6', type: QuestionType.Multiple, question: '甲午，对中国人民和中华民族具有特殊含义，在我国近代史上也具有特殊含义。1894年7月，日本发动甲午战争，清朝在战争中战败。这场战争对中国的影响主要有（ ）。', options: ['A.中国海关的行政权落入外国人手中', 'B.中国人开始有了普遍的民族意识觉醒', 'C.台湾被日本侵占', 'D.帝国主义列强掀起瓜分中国的狂潮'], answer: ['B', 'C', 'D'] },
      { id: 'c1-m-7', type: QuestionType.Multiple, question: '第二次鸦片战争中，清政府被迫签订了（ ）不平等条约：', options: ['A.《南京条约》', 'B.《天津条约》', 'C.《北京条约》', 'D.《瑷珲条约》'], answer: ['B', 'C', 'D'] },
      { id: 'c1-m-8', type: QuestionType.Multiple, question: '袁世凯死后，资本—帝国主义分别扶植的各派军阀的首领有( ) 。', options: ['A.段祺瑞', 'B.冯国璋', 'C.张作霖', 'D.曹锟'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-9', type: QuestionType.Multiple, question: '甲午战争后，帝国主义对华实行商品倾销和资本输出。资本输出的主要方式有（ ）。', options: ['A.办工厂', 'B.修铁路', 'C.开矿山', 'D. 设银行'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-10', type: QuestionType.Multiple, question: '帝国主义对华侵略，包括（ ）。', options: ['A.军事侵略', 'B.政治控制', 'C.经济掠夺', 'D.文化渗透'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-11', type: QuestionType.Multiple, question: '下列叙述，与广学会有关的是（ ）。', options: ['A.基督教在中国设立的最大的出版机构', 'B.英国传教士李提摩太主持过广学会，翻译的《泰西新史揽要》美化帝国主义的侵略', 'C.发行的刊物《万国公报》', 'D.该刊主编、美国传教士林乐知发表《印度隶英十二益说》，主张把英国的殖民统治制度搬到中国来'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-12', type: QuestionType.Multiple, question: '19 世纪70至80年代，中国陷入边疆危机的地区主要包括( )。', options: ['A.西北', 'B.西南', 'C.东北', 'D.东南'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-13', type: QuestionType.Multiple, question: '帝国主义瓜分中国图谋破产的原因包括( )。', options: ['A.列强之间的矛盾和相互制约', 'B.中国人民的反侵略斗争', 'C.帝国主义国家中正义力量的干涉', 'D.中国自给自足的经济社会结构'], answer: ['A', 'B'] },
      { id: 'c1-m-14', type: QuestionType.Multiple, question: '19 世纪70年代以后，主张学习西方科学技术的同时，也要吸纳西方的政治、经济学说，其主要代表人物有( )。', options: ['A.王韬', 'B.薛福成', 'C.郑观应', 'D.马建忠'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-15', type: QuestionType.Multiple, question: '近代西方列强对中国的侵略，在军事方面的侵略包括（ ）。', options: ['A.发动侵略战争，屠杀中国人民', 'B.侵占中国领土，划分势力范围', 'C.勒索赔款，抢夺财富', 'D.控制中国的内政'], answer: ['A', 'B'] },
      { id: 'c1-m-16', type: QuestionType.Multiple, question: '近代西方列强对中国的侵略，在经济方面的侵略包括（ ）。', options: ['A.控制中国的通商口岸', 'B.剥夺中国的关税和自主权', 'C.实行商品倾销和资本输出', 'D.操纵中国的经济命脉'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-17', type: QuestionType.Multiple, question: '近代以来，世界主要资本—帝国主义国家几乎都侵略国中国，从中国内部因素来分析，反侵略战争失败的两个原因，包括（ ）。', options: ['A.社会制度腐败', 'B.经济技术落后', 'C.全国人民不够团结', 'D.敌我力量悬殊'], answer: ['A', 'B'] },
      { id: 'c1-m-18', type: QuestionType.Multiple, question: '中国封建社会出现的“盛世”主要有( )。', options: ['A.文景之治', 'B.贞观之治', 'C.开元之治', 'D.康雍乾盛世'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-19', type: QuestionType.Multiple, question: '“康乾盛世”是指清朝（ ）百余年的历史。', options: ['A.顺治', 'B.康熙', 'C.雍正', 'D.乾隆'], answer: ['B', 'C', 'D'] },
      { id: 'c1-m-20', type: QuestionType.Multiple, question: '1840 年鸦片战争后，清政府被迫与列强签订了一批不平等条约，其中主要有( )。', options: ['A.《北京条约》', 'B.《望厦条约》', 'C.《黄埔条约》', 'D.《南京条约》'], answer: ['B', 'C', 'D'] },
      { id: 'c1-m-21', type: QuestionType.Multiple, question: '近代中国固有的阶级是( )。', options: ['A.地主阶级', 'B.农民阶级', 'C.工人阶级', 'D.资产阶级'], answer: ['A', 'B'] },
      { id: 'c1-m-22', type: QuestionType.Multiple, question: '近代中国新出现的阶级是( )。', options: ['A.地主阶级', 'B.农民阶级', 'C.工人阶级', 'D.资产阶级'], answer: ['C', 'D'] },
      { id: 'c1-m-23', type: QuestionType.Multiple, question: '近代中国社会占支配地位的主要矛盾是( )。', options: ['A.帝国主义与中华民族的矛盾', 'B.无产阶级与资产阶级的矛盾', 'C.资产阶级与地主的矛盾', 'D.封建主义与人民大众的矛盾'], answer: ['A', 'D'] },
      { id: 'c1-m-24', type: QuestionType.Multiple, question: '中国工人阶级的特殊优点包括( )。', options: ['A.革命性最强', 'B.深受帝国主义、封建主义、资产阶级三重压迫', 'C.与广大农民有天然联系', 'D.地区、行业集中、便于组织'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-25', type: QuestionType.Multiple, question: '中国民族资产阶级主要是( )投资新式企业转化而来。', options: ['A.买办', 'B.商人', 'C.地主', 'D.官僚'], answer: ['A', 'B', 'C', 'D'] },
      { id: 'c1-m-26', type: QuestionType.Multiple, question: '中国工人阶级的主要来源是( )。', options: ['A.失业农民', 'B.手工业者', 'C.商人', 'D.城市贫民'], answer: ['A', 'B', 'D'] },
      { id: 'c1-m-27', type: QuestionType.Multiple, question: '近代以来中华民族必须完成的两大历史任务包括（）。', options: ['A.争得民族独立和人民解放', 'B. 实现国家的富强和人民的富裕', 'C.推翻封建帝制', 'D.消灭剥削和压迫'], answer: ['A', 'B'] }
    ]
  },
  {
    id: 'ch2',
    title: '第二章 不同社会力量对国家出路的早期探索',
    questions: [
        // 单选题 (50道)
        { id: 'c2-s-1', type: QuestionType.Single, question: '从适应当时世界历史的角度来看，以下著作最具有进步意义的是( )。', options: ['A.《海国图志》', 'B.《原道醒世训》', 'C.《天朝田亩制度》', 'D.《资政新篇》'], answer: ['D'] },
        { id: 'c2-s-2', type: QuestionType.Single, question: '1851 年，太平天国运动爆发，当时的清朝皇帝是（ ）。', options: ['A. 道光帝', 'B. 同治帝', 'C. 咸丰帝', 'D. 光绪帝'], answer: ['C'] },
        { id: 'c2-s-3', type: QuestionType.Single, question: '中国旧式农民战争的最高峰是（ ）。', options: ['A.义和团运动', 'B.三元里人民抗英斗争', 'C.太平天国运动', 'D.反教会斗争'], answer: ['C'] },
        { id: 'c2-s-4', type: QuestionType.Single, question: '近代对国家出路的早期探索是（ ）。', options: ['A.太平天国运动', 'B.新文化运动', 'C.五四运动', 'D.一二九运动'], answer: ['A'] },
        { id: 'c2-s-5', type: QuestionType.Single, question: '太平天国领袖洪秀全创立的宗教是( )。', options: ['A.基督教', 'B.拜上帝教', 'C.白莲教', 'D.萨满教'], answer: ['B'] },
        { id: 'c2-s-6', type: QuestionType.Single, question: '太平天国失败的根本原因是（ ）。', options: ['A.农民阶级的局限性', 'B.战略失误导致北伐失利', 'C.遭到中外反动势力的联合绞杀', 'D.领导集团的内部斗争'], answer: ['A'] },
        { id: 'c2-s-7', type: QuestionType.Single, question: '以下内容不属于《资政新篇》的是( ) 。', options: ['A.各省设新闻馆', 'B.提倡兴办新式学校', 'C.严禁买卖人口和吸食鸦片', 'D.撤并政府机构，裁汰冗员'], answer: ['D'] },
        { id: 'c2-s-8', type: QuestionType.Single, question: '太平天国运动的革命纲领是（ ）。', options: ['A.《四洲志》', 'B.《定国是诏》', 'C.《应诏统筹全局折》', 'D.《天朝田亩制度》'], answer: ['D'] },
        { id: 'c2-s-9', type: QuestionType.Single, question: '太平天国正式建立起与清政府对峙的农民政权开始于（ ）。', options: ['A.金田起义', 'B.永安建制', 'C.洪秀全东乡称天王', 'D.定都天京'], answer: ['D'] },
        { id: 'c2-s-10', type: QuestionType.Single, question: '太平天国运动面对着中国历史上历次农民战争所不曾有的新情况，“新情况”是指（ ）。', options: ['A.尖锐的阶级矛盾', 'B.满汉地主阶级的共同镇压', 'C.内讧导致力量削弱', 'D.中外反动势力的联合镇压'], answer: ['D'] },
        { id: 'c2-s-11', type: QuestionType.Single, question: '下列太平天国的诸活动中，能与当时世界历史潮流同步的是（ ）。', options: ['A.颁布《天朝田亩制度》', 'B.洪仁王干的《资政新篇》', 'C.严惩外国侵略者', 'D.反对腐朽没落的封建统治'], answer: ['B'] },
        { id: 'c2-s-12', type: QuestionType.Single, question: '《海国图志》和《资政新篇》有相似之处是都主张（ ）。', options: ['A.进行政治、经济、文化制度的改革', 'B.向西方学习', 'C.进行资产阶级思想启蒙运动', 'D.在中国发展资本主义'], answer: ['B'] },
        { id: 'c2-s-13', type: QuestionType.Single, question: '在向西方学习的问题上，《资政新篇》与《海国图志》的主要区别在于( )。', options: ['A.是否学习西方先进技术', 'B.是否抵御外来侵略', 'C.是否发展资本主义', 'D.是否翻译外国书报'], answer: ['C'] },
        { id: 'c2-s-14', type: QuestionType.Single, question: '曾担任中国使臣，出访欧美的蒲安臣是（ ）。', options: ['A.英国人', 'B.美国人', 'C.法国人', 'D.德国人'], answer: ['B'] },
        { id: 'c2-s-15', type: QuestionType.Single, question: '洋务派所办的民用工业其生产的主要目的是（ ）。', options: ['A.满足军事工业的需要', 'B.抵制外国经济势力的扩张', 'C.赚取利润，增强经济实力', 'D.培养人材，发展资本主义'], answer: ['A'] },
        { id: 'c2-s-16', type: QuestionType.Single, question: '由李鸿章管辖的清政府海军主力是（ ）。', options: ['A.广东水师', 'B.北洋水师', 'C.南洋水师', 'D.福建水师'], answer: ['B'] },
        { id: 'c2-s-17', type: QuestionType.Single, question: '左宗棠开办的近代军事工业是（ ）。', options: ['A.湖北织布局', 'B.继昌隆缫丝厂', 'C.福州船政局', 'D.发昌机器厂'], answer: ['C'] },
        { id: 'c2-s-18', type: QuestionType.Single, question: '洋务运动后期，洋务派打出的旗号是（ ）。', options: ['A.“师夷长技以制夷”', 'B.“自强”', 'C.“扶清灭洋”', 'D.“求富”'], answer: ['D'] },
        { id: 'c2-s-19', type: QuestionType.Single, question: '洋务派的主张是（ ）。', options: ['A.利用西方先进科学技术来维护清朝统治', 'B.利用西方先进技术抵抗西方侵略', 'C.利用西方先进思想改造中国社会', 'D.引进西方先进制度改造中国社会'], answer: ['A'] },
        { id: 'c2-s-20', type: QuestionType.Single, question: '洋务运动前期李鸿章创办的近代军事工业有（ ）。', options: ['A.安庆军械所', 'B.江南制造总局', 'C.福州船政局', 'D.天津机器制造局'], answer: ['B'] },
        { id: 'c2-s-21', type: QuestionType.Single, question: '对洋务运动的下列评价中，不正确的是（ ）。', options: ['A.客观上刺激中国资本主义的发展', 'B.对外国经济的扩张起了一些抵制作用', 'C.使中国走上资本主义道路', 'D.引进西方先进技术，培养了一批科技人才'], answer: ['C'] },
        { id: 'c2-s-22', type: QuestionType.Single, question: '19 世纪60年代以后产生的早期维新思想的代表人物有（ ）。', options: ['A.张之洞、丁汝昌', 'B.邓世昌、王韬', 'C.王韬、郑观应', 'D.郑观应、谭嗣同'], answer: ['C'] },
        { id: 'c2-s-23', type: QuestionType.Single, question: '据统计，“上海轮船招商局创办三年内，外轮就损失了1300万两；湖北官办织布局开办后，江南海关每年洋布进口减少了10万匹”，这说明洋务运动（ ）。', options: ['A.改变了中国对外贸易入超的局面', 'B.加快了长江流域民族工业的发展', 'C.实现了“自强”、“求富”的目的', 'D.对外国经济势力扩张有一定抵制作用'], answer: ['D'] },
        { id: 'c2-s-24', type: QuestionType.Single, question: '《马关条约》签定后，日本归还辽东半岛的主要原因是（ ）。', options: ['A.实力不如俄、德、法', 'B.贪图中国3000万两白银', 'C.李鸿章请求英国调解成功', 'D.清政府利用西方列强与日本的矛盾'], answer: ['A'] },
        { id: 'c2-s-25', type: QuestionType.Single, question: '刺激列强瓜分中国的事件是（ ）。', options: ['A.《北京条约》的签订', 'B.《中法新约》的签订', 'C.《马关条约》的签订', 'D.德国强占胶州湾'], answer: ['D'] },
        { id: 'c2-s-26', type: QuestionType.Single, question: '戊戌变法的阶级基础是（ ）。', options: ['A.光绪帝和部分清朝官员', 'B.开明地主和爱国知识分子', 'C.爱国知识分子与民族资产阶级', 'D.开明地主和民族资产阶级'], answer: ['C'] },
        { id: 'c2-s-27', type: QuestionType.Single, question: '维新派同顽固派论战的问题不包括（ ）。', options: ['A.要不要提倡西学', 'B.要不要兴民权，实行君主立宪', 'C.要不要变法', 'D.要不要社会革命'], answer: ['D'] },
        { id: 'c2-s-28', type: QuestionType.Single, question: '戊戌政变后，新政中被保留下来的只有（ ）。', options: ['A.农工商总局', 'B.京师大学堂', 'C.译书局', 'D.铁路矿务局'], answer: ['B'] },
        { id: 'c2-s-29', type: QuestionType.Single, question: '下列对戊戌变法的评价中，不正确的是（ ）。', options: ['A.是中国近代史上首次思想解放运动', 'B.是一次资产阶级的改良运动', 'C.是一次救亡图存的爱国运动', 'D.具有广泛群众基础的变法运动'], answer: ['D'] },
        { id: 'c2-s-30', type: QuestionType.Single, question: '中国民族资产阶级作为新的政治力量开始登上历史舞台，是在19世纪( )。', options: ['A 60年代', 'B 70年代', 'C 80年代', 'D 90年代'], answer: ['D'] },
        { id: 'c2-s-31', type: QuestionType.Single, question: '义和团反帝爱国运动的直接意义是（ ）。', options: ['A 打击了清政府的反动统治，加速了它的灭亡', 'B 暴露了清政府的卖国本质，促进了人民的觉醒', 'C 粉碎了帝国主义瓜分中国的的狂妄计划', 'D 促进了资产阶级革命团体的建立'], answer: ['C'] },
        { id: 'c2-s-32', type: QuestionType.Single, question: '义和团运动首先兴起于（ ）。', options: ['A 山东', 'B 直隶', 'C 天津', 'D 北京'], answer: ['A'] },
        { id: 'c2-s-33', type: QuestionType.Single, question: '义和团“扶清灭洋”口号突出反映了当时社会最主要矛盾是（ ）。', options: ['A.帝国主义与中华民族的矛盾', 'B.帝国主义与清政府的矛盾', 'C.封建主义与人民大众的矛盾', 'D.农民阶级与教会势力的矛盾'], answer: ['A'] },
        { id: 'c2-s-34', type: QuestionType.Single, question: '标志着以慈禧为首的清政府已彻底放弃了抵抗外国侵略者的条约是（ ）。', options: ['A.《中英南京条约》', 'B.《中俄条约》', 'C.《辛丑条约》', 'D.《马关条约》'], answer: ['C'] },
        { id: 'c2-s-35', type: QuestionType.Single, question: '太平天国革命运动制定的第一个纲领性文件是（ ）。', options: ['A.《资政新篇》', 'B.《原道救世歌》', 'C.《原道醒世训》', 'D.《天朝田亩制度》'], answer: ['D'] },
        { id: 'c2-s-36', type: QuestionType.Single, question: '下列关于洋务运动的作用说法不正确的是（ ）。', options: ['A.使中国走上了富强的道路', 'B.刺激了中国资本主义的发展', 'C.一定程度上抵制了外国经济势力的扩张', 'D.引进了一些先进生产技术'], answer: ['A'] },
        { id: 'c2-s-37', type: QuestionType.Single, question: '戊戌变法是一场资产阶级性质的改良运动，这是因为变法的政令（ ）。', options: ['A.触及了封建制度的根本', 'B.采纳了维新派提出的开国会等政治主张', 'C.一定程度上反映了资产阶级的政治和经济诉求', 'D.带有彻底性和不妥协性'], answer: ['C'] },
        { id: 'c2-s-38', type: QuestionType.Single, question: '1898 年 9 月，慈禧太后发动政变...政变的实质反映了（ ）。', options: ['A.统治阶级内部争权夺势的斗争', 'B.开明地主和封建顽固势力的斗争', 'C.资产阶级和封建旧势力的斗争', 'D.光绪帝和慈禧太后争夺统治权的斗争'], answer: ['C'] },
        { id: 'c2-s-39', type: QuestionType.Single, question: '戊戌维新运动突出的历史功绩在于（ ）。', options: ['A.挽救民族危亡', 'B.推动政治改革', 'C.发展社会经济', 'D.促进思想启蒙'], answer: ['D'] },
        { id: 'c2-s-40', type: QuestionType.Single, question: '为中国的近代化开辟了道路的是（ ）。', options: ['A．洋务运动', 'B．戊戌变法', 'C．辛亥革命', 'D．新文化运动'], answer: ['A'] },
        { id: 'c2-s-41', type: QuestionType.Single, question: '太平天国由盛转衰的分水岭的标志性事件（ ）。', options: ['A.定都天京', 'B.天京事变', 'C.永安建制', 'D.创立拜上帝教'], answer: ['B'] },
        { id: 'c2-s-42', type: QuestionType.Single, question: '最能体现太平天国社会理想和农民起义特色的纲领性文件是（ ）。', options: ['A.《原道救世歌》', 'B.《资政新篇》', 'C.《天朝田亩制度》', 'D.《原道醒世训》'], answer: ['C'] },
        { id: 'c2-s-43', type: QuestionType.Single, question: '太平天国后期颁布的社会发展方案是（ ）。', options: ['A.《原道救世歌》', 'B.《资政新篇》', 'C.《天朝田亩制度》', 'D.《原道醒世训》'], answer: ['B'] },
        { id: 'c2-s-44', type: QuestionType.Single, question: '在 19 世纪中叶的亚洲民族解放运动中，其中时间最久、规模最大、影响最深的一次是（ ）。', options: ['A.捻军起义', 'B.回民起义', 'C.太平天国起义', 'D.西南少数民族起义'], answer: ['C'] },
        { id: 'c2-s-45', type: QuestionType.Single, question: '洋务派在中央的代表是（ ）。', options: ['A.曾国藩', 'B.李鸿章', 'C.崇厚', 'D.奕䜣'], answer: ['D'] },
        { id: 'c2-s-46', type: QuestionType.Single, question: '对洋务派兴办洋务事业的指导思想最先作出比较完整表述的是（ ）。', options: ['A.冯桂芬', 'B.张之洞', 'C.王韬', 'D.郑观应'], answer: ['A'] },
        { id: 'c2-s-47', type: QuestionType.Single, question: '下面最能体现维新派的政治主张的是（ ）。', options: ['A.中体西用', 'B.君主立宪', 'C.预备立宪', 'D.民主共和'], answer: ['B'] },
        { id: 'c2-s-48', type: QuestionType.Single, question: '维新派代表康有为所著《孔子改制考》，其本质是（ ）。', options: ['A.皇权变法', 'B.托古改制', 'C.君主立宪', 'D.否定封建主义'], answer: ['B'] },
        { id: 'c2-s-49', type: QuestionType.Single, question: '下面最能体现光绪皇帝颁布的政令和措施并未触及封建制度的根本的是（ ）。', options: ['A.政令中并未体现开国会、定宪法的主张', 'B.皇权变法', 'C.实行君主立宪', 'D.否定封建主义'], answer: ['A'] },
        { id: 'c2-s-50', type: QuestionType.Single, question: '戊戌政变后，唯一被保留了下来的是（ ）。', options: ['A.时务学堂', 'B.京师大学堂', 'C.万木草堂', 'D.船政学堂'], answer: ['B'] },

        // 多选题 (40道)
        { id: 'c2-m-1', type: QuestionType.Multiple, question: '洋务运动的目的包括（ ）。', options: ['A.镇压太平天国农民起义', 'B.维护清政府的统治', 'C.学习西方的先进技术', 'D.加强海防、边防，抵御外国侵略'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-2', type: QuestionType.Multiple, question: '维新派和守旧派之间的论战所围绕的主要问题是（ ）。', options: ['A.要不要变法', 'B.要不要推翻帝制，实行共和', 'C.要不要兴民权、设议院，实行君主立宪', 'D.要不要废八股、改科举和兴学堂'], answer: ['A', 'C', 'D'] },
        { id: 'c2-m-3', type: QuestionType.Multiple, question: '《天朝田亩制度》的主要内容有（ ）。', options: ['A．按人口平均分配土地', 'B．分得土地的农民都要参加农副业生产劳动', 'C．支出由国库统一分配', 'D．禁朋党之弊'], answer: ['A', 'B', 'C'] },
        { id: 'c2-m-4', type: QuestionType.Multiple, question: '洋务派兴办的官督商的办民用企业主要有（ ）。', options: ['A.轮船招商局', 'B.开平矿务局', 'C.天津电报局', 'D.上海机器织布局'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-5', type: QuestionType.Multiple, question: '维新派与洋务派分歧的实质是（ ）。', options: ['A．要不要社会革命', 'B．要不要以革命手段推翻清王朝', 'C．要不要学习西方的政治制度', 'D．要不要学习西方的思想文化'], answer: ['C'] },
        { id: 'c2-m-6', type: QuestionType.Multiple, question: '兴办洋务的重要基地有（ ）。', options: ['A.上海', 'B.北京', 'C.天津', 'D.南京'], answer: ['A', 'C', 'D'] },
        { id: 'c2-m-7', type: QuestionType.Multiple, question: '1851 年 9 月，太平军攻占永安，在永安封王建制...其他诸王有（ ）。', options: ['A.西王萧朝贵', 'B.南王冯云山', 'C.北王韦昌辉', 'D.翼王石达开'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-8', type: QuestionType.Multiple, question: '早期维新思想家的代表人物主要有（ ）。', options: ['A.郑观应', 'B.王韬', 'C.严复', 'D.马建忠'], answer: ['A', 'B', 'D'] },
        { id: 'c2-m-9', type: QuestionType.Multiple, question: '十九世纪下半叶...洋务运动历时30年。其最终失败的主要原因有（ ）。', options: ['A.指导思想的封建性', 'B.对外国具有依赖性', 'C.资金人才的匮乏性', 'D.洋务企业管理的腐朽性'], answer: ['A', 'B', 'D'] },
        { id: 'c2-m-10', type: QuestionType.Multiple, question: '洋务派代表人物有（ ）。', options: ['A. 左宗棠', 'B.李鸿章', 'C.张之洞', 'D.曾国藩'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-11', type: QuestionType.Multiple, question: '维新派“无力回天”的原因主要是（ ）。', options: ['A.他们提倡全面学习“西方”，彻底否定“中学”', 'B.他们遭到了以慈禧太后为首的强大的守旧势力的反击和镇压', 'C.他们惧怕人民群众，把改革的全部希望寄托在一个没有实权的皇帝身上', 'D.他们不敢触动封建主义的经济基础'], answer: ['B', 'C', 'D'] },
        { id: 'c2-m-12', type: QuestionType.Multiple, question: '19 世纪末叶，维新派创办的宣传变法维新思想的报刊有（ ）。', options: ['A.《强学报》', 'B.《国闻报》', 'C.《时务报》', 'D.《湘报》'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-13', type: QuestionType.Multiple, question: '1898 年 9 月，慈禧发动戊戌政变，被杀害的维新派人士有（ ）。', options: ['A.谭嗣同', 'B.杨锐', 'C.刘光第', 'D.康广仁'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-14', type: QuestionType.Multiple, question: '太平天国的革命纲领有（ ） 。', options: ['A.《原道救世歌》', 'B.《资政新编》', 'C.《原道觉世训》', 'D.《天朝田亩制度》'], answer: ['B', 'D'] },
        { id: 'c2-m-15', type: QuestionType.Multiple, question: '在太平天国革命中，参与镇压太平军的外国侵略者是（ ）。', options: ['A.常胜军', 'B.常安军', 'C.常捷军', 'D.英军'], answer: ['A', 'C', 'D'] },
        { id: 'c2-m-16', type: QuestionType.Multiple, question: '洋务运动中，清王朝曾建立的海军是（ ） 。', options: ['A.北洋水师', 'B.南洋水师', 'C.福建水师', 'D.广东水师'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-17', type: QuestionType.Multiple, question: '1891—1892 年，康有为写成变法维新的两篇理论著作是（ ）。', options: ['A.《仁学》', 'B.《救亡决论》', 'C.《新学伪经考》', 'D.《孔子改制考》'], answer: ['C', 'D'] },
        { id: 'c2-m-18', type: QuestionType.Multiple, question: '洋务运动的进步作用包括（ ）。', options: ['A．引进西方一些近代生产技术', 'B.是中国近代化的开端', 'C．刺激了中国资本主义的产生', 'D.对外国经济侵略作了些抵制'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-19', type: QuestionType.Multiple, question: '洋务运动的一个重要内容就是创办新式学堂，主要有（ ）。', options: ['A．翻译学堂', 'B.工艺学堂', 'C.军事学堂', 'D.法政学堂'], answer: ['A', 'B', 'C'] },
        { id: 'c2-m-20', type: QuestionType.Multiple, question: '“中学为体，西学为用”是指（ ）。', options: ['A．以中国封建伦理纲常所维护的统治秩序为主体', 'B．以希望的近代工业和技术为辅助', 'C．要加强海防、边防', 'D．要传播西方科学技术知识'], answer: ['A', 'B'] },
        { id: 'c2-m-21', type: QuestionType.Multiple, question: '洋务运动中最早兴办的兵工厂有（ ）。', options: ['A．江南制造局', 'B.福建船政局', 'C.天津机器局', 'D.金陵机器局'], answer: ['A', 'C', 'D'] },
        { id: 'c2-m-22', type: QuestionType.Multiple, question: '维新派与守旧派的论战主要围绕的问题有（ ）。', options: ['A.要不要进行资产阶级革命', 'B.要不要变法', 'C.要不要兴民权、设议院、实行君主立宪', 'D.要不要废除八股、改革科举和兴西学'], answer: ['B', 'C', 'D'] },
        { id: 'c2-m-23', type: QuestionType.Multiple, question: '1890 年，李鸿章建立上海机器织布局后规定...这表明（ ）。', options: ['A.洋务运动有压制民族资本主义的一面', 'B.在清政府的扶植下中国出现了垄断资本主义', 'C.要真正发展民族工业必须推翻封建制度', 'D.洋务运动具有浓厚的封建性'], answer: ['A', 'D'] },
        { id: 'c2-m-24', type: QuestionType.Multiple, question: '维新派本身的局限性突出地表现在（ ）。', options: ['A．不敢否定封建主义', 'B．对帝国主义抱有幻想', 'C．惧怕人民群众', 'D．不敢公开提出打倒帝国主义'], answer: ['A', 'B', 'C'] },
        { id: 'c2-m-25', type: QuestionType.Multiple, question: '19 世纪末的戊戌维新运动（ ）。', options: ['A.是中国资产阶级参与国家政权的开始', 'B.以建立资本主义的政治经济制度为目标', 'C.维新派把维新变法与救亡图存相结合', 'D.使中国现代化历程深入到政治领域'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-26', type: QuestionType.Multiple, question: '洋务派所办的民用工业其生产的目的是（ ） 。', options: ['A．辅助军工企业的发展', 'B．抵制外国经济势力的扩张', 'C．赚取利润', 'D．发展资本主义'], answer: ['A', 'B', 'C'] },
        { id: 'c2-m-27', type: QuestionType.Multiple, question: '从 19 世纪60年代——90年代，洋务派举办的洋务事业主要有（ ）。', options: ['A．兴办军用企业', 'B.兴办民用企业', 'C.建立新式海陆军', 'D.创办新式学堂'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-28', type: QuestionType.Multiple, question: '《天朝田亩制度》和《资政新篇》...共同的局限性是（ ）。', options: ['A．不能对当时的社会主要矛盾作出正确判断', 'B．带有强烈的小农意识', 'C．只学习西方先进技术', 'D．缺乏坚实的社会基础'], answer: ['A', 'D'] },
        { id: 'c2-m-29', type: QuestionType.Multiple, question: '魏源的“师夷长技以制夷”与洋务派“师夷长技以自强”（ ）。', options: ['A.有内在的一致性和继承性', 'B.都有抵御外来侵略的意图', 'C.都主要体现了地主阶级的要求', 'D.在当时都有进步意义'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-30', type: QuestionType.Multiple, question: '与以往的农民战争相比，太平天国运动新的时代特点表现在（ ）。', options: ['A.运动规模空前巨大', 'B.反封建同时反侵略', 'C.《天朝田亩制度》的平均主义理想', 'D.《资政新篇》的资本主义色彩'], answer: ['B', 'D'] },
        { id: 'c2-m-31', type: QuestionType.Multiple, question: '为介绍外国变法的经验，康有为向光绪皇帝进呈的著作包括（ ）。', options: ['A.《日本变政考》', 'B.《俄彼得变政记》', 'C.《波兰分灭记》', 'D.《泰西新史揽要》'], answer: ['A', 'B', 'C'] },
        { id: 'c2-m-32', type: QuestionType.Multiple, question: '近代以后...不同社会力量对国家出路的早期探索，包括（ ）。', options: ['A．太平天国运动', 'B.洋务运动', 'C.维新运动', 'D.辛亥革命'], answer: ['A', 'B', 'C'] },
        { id: 'c2-m-33', type: QuestionType.Multiple, question: '洋务运动的兴起，与（ ）有关。', options: ['A．太平天国起义', 'B.义和团运动', 'C.捻军起义', 'D.小刀会起义'], answer: ['A', 'C', 'D'] },
        { id: 'c2-m-34', type: QuestionType.Multiple, question: '戊戌维新运动的失败表明，带给先进的中国人的启示，包括（ ）。', options: ['A.改良的道路行不通', 'B.必须用革命的手段', 'C.必须同封建守旧势力相结合', 'D.必须寻求帝国主义的帮助'], answer: ['A', 'B'] },
        { id: 'c2-m-35', type: QuestionType.Multiple, question: '太平天国后期担任军事指挥的青年将领有( )。', options: ['A.杨秀清', 'B.冯云山', 'C.陈玉成', 'D.李秀成'], answer: ['C', 'D'] },
        { id: 'c2-m-36', type: QuestionType.Multiple, question: '下面哪些制度属于太平天国运动期间颁布的（ ）。', options: ['A.《天朝田亩制度》', 'B.《定国是诏》', 'C. 《海国图志》', 'D.《资政新篇》'], answer: ['A', 'D'] },
        { id: 'c2-m-37', type: QuestionType.Multiple, question: '太平天国的领导者们希望建立怎样的理想社会（ ）。', options: ['A.无处不均匀', 'B.无处不暖饱', 'C.有田同耕，有饭同食', 'D.有衣同穿，有钱同使'], answer: ['C', 'D'] },
        { id: 'c2-m-38', type: QuestionType.Multiple, question: '下面哪些历史人物以大无畏精神为变法维新而献身（ ）。', options: ['A.谭嗣同', 'B.康有为', 'C.康广仁', 'D.刘光第'], answer: ['A', 'C', 'D'] },
        { id: 'c2-m-39', type: QuestionType.Multiple, question: '在维新派的推动下，形成了哪些文化革新运动（ ）。', options: ['A.诗界革命', 'B.文体革命', 'C.史学革命', 'D.小说界革命和戏剧改良'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c2-m-40', type: QuestionType.Multiple, question: '维新派与守旧派的论战，实质上是哪两种思想的第一次正面交锋（ ）。', options: ['A.资产阶级思想', 'B.社会主义思想', 'C.封建主义思想', 'D.保守主义思想'], answer: ['A', 'C'] }
    ]
  },
  {
    id: 'ch3',
    title: '第三章 辛亥革命与君主专制制度的终结',
    questions: [
        // 单选题 (29道)
        { id: 'c3-s-1', type: QuestionType.Single, question: '以下资产阶级的政治团体成立最早的是（ ）。', options: ['A.强学会', 'B.保国会', 'C.兴中会', 'D.南学会'], answer: ['C'] },
        { id: 'c3-s-2', type: QuestionType.Single, question: '孙中山组织兴中会是在（ ）。', options: ['A.1892 年', 'B.1893 年', 'C.1894年', 'D.1895 年'], answer: ['C'] },
        { id: 'c3-s-3', type: QuestionType.Single, question: '“驱除鞑虏,恢复中国,创立合众政府”的革命纲领是孙中山先生在组织( )时提出的。', options: ['A．华兴会', 'B.光复会', 'C.同盟会', 'D.兴中会'], answer: ['D'] },
        { id: 'c3-s-4', type: QuestionType.Single, question: '孙中山提出的资产阶级民主革命纲领后来称为“三民主义”,即( )主义。', options: ['A.民族、民权、民生', 'B.民主、民权、民族', 'C.民权、民生、民主', 'D.民生、民族、民主'], answer: ['A'] },
        { id: 'c3-s-5', type: QuestionType.Single, question: '近代中国首先提出“振兴中华”口号的是( )。', options: ['A.康有为', 'B.洪秀全', 'C.林则徐', 'D.孙中山'], answer: ['D'] },
        { id: 'c3-s-6', type: QuestionType.Single, question: '《驳康有为论革命书》作者是（ ）。', options: ['A.邹容', 'B.陈独秀', 'C.陈天华', 'D.章炳麟'], answer: ['D'] },
        { id: 'c3-s-7', type: QuestionType.Single, question: '中国第一个全国性的统一的资产阶级革命政党是( )。', options: ['A.兴中会', 'B.同盟会', 'C.国民党', 'D.文学社'], answer: ['B'] },
        { id: 'c3-s-8', type: QuestionType.Single, question: '中国同盟会的成立标志着中国资产阶级民主革命进入了一个新阶段。这里的“新阶段”主要是指（ ）。', options: ['A.资产阶级革命派开始正式形成', 'B.开始与保皇派展开激烈论战', 'C.革命派开始积极发动武装起义', 'D.革命有了统一的领导和纲领'], answer: ['D'] },
        { id: 'c3-s-9', type: QuestionType.Single, question: '中国历史上第一部具有资产阶级共和国宪法性质的法典是（ ）。', options: ['A.《钦定宪法大纲》', 'B.《中华民国临时约法》', 'C.《资政新篇》', 'D.《中华民国约法》'], answer: ['B'] },
        { id: 'c3-s-10', type: QuestionType.Single, question: '武昌起义爆发后，列强的态度...造成这一系列变化的决定性因素是（ ）。', options: ['A.帝国主义在华利益的得失', 'B.革命形势的迅速发展', 'C.袁世凯卖国求荣', 'D.清政府土崩瓦解'], answer: ['A'] },
        { id: 'c3-s-11', type: QuestionType.Single, question: '宋教仁案的发生从本质上反映了（ ）。', options: ['A.民主共和与专制独裁的矛盾', 'B.美、日对中国的矛盾', 'C.统治集团内部的斗争', 'D.国民党与北洋军阀的矛盾'], answer: ['A'] },
        { id: 'c3-s-12', type: QuestionType.Single, question: '1915 年日本向袁世凯提出“二十一条”要求的主要目的是（ ）。', options: ['A.支持袁世凯复辟', 'B.企图独占中国', 'C.抵制美国的扩张', 'D.夺取德国的“势力范围”'], answer: ['B'] },
        { id: 'c3-s-13', type: QuestionType.Single, question: '辛亥革命后，孙中山领导的南京临时政府对清政府与帝国主义签订的不平等条约的态度是（ ）。', options: ['A.概不承认', 'B.全部承认', 'C.重订新约', 'D.部分承认'], answer: ['B'] },
        { id: 'c3-s-14', type: QuestionType.Single, question: '有人说：“20世纪初期的立宪派实际上成了封建主义的同盟军”。持此观点的依据是（ ）。', options: ['A.立宪派已成为封建势力的代理人', 'B.立宪派维护清王朝的统治', 'C.立宪派具有软弱性和妥协性', 'D.立宪派维护君主专制制度'], answer: ['B'] },
        { id: 'c3-s-15', type: QuestionType.Single, question: '我国的科举制度正式废除于（ ）。', options: ['A.1904', 'B.1905', 'C.1906', 'D.1908'], answer: ['B'] },
        { id: 'c3-s-16', type: QuestionType.Single, question: '兴中会的革命纲领不包括（ ）。', options: ['A.驱除鞑虏', 'B.恢复中国', 'C.创立合众政府', 'D.平均地权'], answer: ['D'] },
        { id: 'c3-s-17', type: QuestionType.Single, question: '为使民主革命思想得到广泛传播，各种宣传革命的书籍报刊纷纷出现，下列不属于此类书籍报刊的是（ ）。', options: ['A.《警世通言》', 'B.《驳康有为论革命书》', 'C.《革命军》', 'D.《猛回头》'], answer: ['A'] },
        { id: 'c3-s-18', type: QuestionType.Single, question: '中国同盟会的机关刊物是（ ）。', options: ['A.《时务报》', 'B.《新民从报》', 'C.《国闻报》', 'D.《民报》'], answer: ['D'] },
        { id: 'c3-s-19', type: QuestionType.Single, question: '下列不属于三民主义的内容的是（ ）。', options: ['A.民族主义', 'B.民权主义', 'C.民生主义', 'D.民主主义'], answer: ['D'] },
        { id: 'c3-s-20', type: QuestionType.Single, question: '革命派与改良派论战的焦点是（ ）。', options: ['A.要不要以革命手段推翻清王朝', 'B.要不要推翻帝制，实行共和', 'C.要不要社会革命', 'D.要不要向西方学习'], answer: ['B'] },
        { id: 'c3-s-21', type: QuestionType.Single, question: '下列武装起义中不属于同盟会发动的是（ ）。', options: ['A.广州起义', 'B.南昌起义', 'C.绍兴起义', 'D.武昌起义'], answer: ['B'] },
        { id: 'c3-s-22', type: QuestionType.Single, question: '辛亥革命的历史意义不包括（ ）。', options: ['A.推翻了清王朝的统治，打击了中外反动势力。', 'B.是一场资产阶级性质的政治改革运动。', 'C.给人们带来一次思想上的解放。', 'D.建立了中国历史上第一个资产阶级共和政府。'], answer: ['B'] },
        { id: 'c3-s-23', type: QuestionType.Single, question: '下列不属于南京临时政府出现的危机的是（ ）。', options: ['A.没有取得人民的支持', 'B.外交上没有取得各国承认', 'C.经济上几乎寸步难行', 'D.袁世凯的武力威胁'], answer: ['A'] },
        { id: 'c3-s-24', type: QuestionType.Single, question: '清帝退位的具体时间是（ ）。', options: ['A.1912.2.2', 'B.1921.2.12', 'C.1912.2.12', 'D.1912.12.2'], answer: ['C'] },
        { id: 'c3-s-25', type: QuestionType.Single, question: '袁世凯最终在（ ）就任临时大总统。', options: ['A.上海', 'B.南京', 'C.武昌', 'D.北京'], answer: ['D'] },
        { id: 'c3-s-26', type: QuestionType.Single, question: '封建军阀的专制统治在政治上表现为（ ）。', options: ['A.竭力维护帝国主义，地主阶级和买办资产阶级的利益', 'B.实行军阀官僚的专制统治', 'C.加强中央集权，制定法律制度', 'D.改革行政机构，裁汰冗员'], answer: ['B'] },
        { id: 'c3-s-27', type: QuestionType.Single, question: '辛亥革命失败的原因不包括（ ）。', options: ['A.没有从根本上提出完整的，正确的政治纲领和社会改革方案。', 'B.没有充分发动和依靠人民群众。', 'C.没有提出彻底的反帝反封建的革命纲领。', 'D.没有建立坚强的革命政党，作为团结一切革命力量的强有力的核心。'], answer: ['A'] },
        { id: 'c3-s-28', type: QuestionType.Single, question: '在孙中山的思想中，“平均地权”“节制资本”属于（ ）。', options: ['A．民族主义', 'B．民权主义', 'C．民生主义', 'D．民主主义'], answer: ['C'] },
        { id: 'c3-s-29', type: QuestionType.Single, question: '毛泽东在谈到辛亥革命时指出...“只把一个皇帝赶跑”是指（ ）。', options: ['A．没有推翻帝制', 'B．反帝反封建的革命任务没有完成', 'C．孙中山没有继续革命', 'D．袁世凯窃取了胜利果实'], answer: ['B'] },

        // 多选题 (23道)
        { id: 'c3-m-1', type: QuestionType.Multiple, question: '20 世纪初，中国民族危机加深体现在（ ）。', options: ['A.列强加强了对清政府的政治控制', 'B.列强竭力扩展在华经济势力', 'C.外国在华投资规模急速扩张', 'Ｄ.铁路、矿山的利权成为列强掠夺的重要目标'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-2', type: QuestionType.Multiple, question: '以孙中山为代表的革命派和以康有为为代表的改良派论战所围绕的主要问题是（ ）。', options: ['A.要不要以革命手段推翻清政府', 'B.要不要推翻帝制，实行共和', 'C.要不要进行社会革命', 'D.要不要向西方学习'], answer: ['A', 'B', 'C'] },
        { id: 'c3-m-3', type: QuestionType.Multiple, question: '下列属于新三民主义内容的有（ ）。', options: ['A.民权为一般平民所共有', 'B.国内各民族一律平等，反帝国主义侵略', 'C.平均地权，节制资本', 'D.实现民主主义的联合战线'], answer: ['A', 'B', 'C'] },
        { id: 'c3-m-4', type: QuestionType.Multiple, question: '面对北洋军阀的黑暗统治，以孙中山为首的资产阶级革命派（ ）。', options: ['A.发动“二次革命”', 'B.组织中华革命党', 'C.发动护国战争', 'D.发动第一次和第二次护法运动'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-5', type: QuestionType.Multiple, question: '继兴中会之后，资产阶级革命团体在各地陆续成立，主要有（ ）。', options: ['A.华兴会', 'B.光复会', 'C.科学补习所', 'D.岳王会'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-6', type: QuestionType.Multiple, question: '资产阶级是近代中国新产生的阶级，主要来自（ ）。', options: ['A.地主', 'B.商人', 'C.买办', 'D.官僚'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-7', type: QuestionType.Multiple, question: '袁世凯为了巩固专制统治，不惜投靠帝国主义，包括（ ）。', options: ['A.向日本借款扩充自己的势力...其中“西原借款”...', 'B.与列强签订“善后大借款”合同', 'C.接受严重损害中国权益的“二十一条”', 'D.与列强签订出卖铁路利权合同'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-8', type: QuestionType.Multiple, question: '袁世凯就任临时大总统后破坏资产阶级民主制度的活动有（ ）。', options: ['A.强迫国会选举他为正式大总统', 'B.解散国会，遣散议员', 'C.炮制《中华民国约法》，用总统制取代内阁制', 'D.修改《总统选举法》以达到无限期连任，并推荐继承人'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-9', type: QuestionType.Multiple, question: '孙中山为了防止袁世凯专制而提出的条件有（ ）。', options: ['A.定都南京', 'B.新总统到南京就职', 'C.遵守临时约法', 'D.清帝退位'], answer: ['A', 'B', 'C'] },
        { id: 'c3-m-10', type: QuestionType.Multiple, question: '武昌起义后，各省独立政权情况复杂，表现为（ ）。', options: ['A.革命党人主动把权力让给立宪派和旧官僚、旧军官', 'B.政权被立宪派和旧官僚、旧军官篡夺', 'C.旧官僚和旧军官改头换面地维持着旧政权', 'D.虽是革命党人掌权，但很快蜕变为新军阀、新官僚'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-11', type: QuestionType.Multiple, question: '在辛亥革命的酝酿阶段,资产阶级革命派领导的爱国运动中,规模较大具有代表性的有（ ）等。', options: ['A.拒俄运动', 'B.保路运动', 'C.抵制美货运动', 'D.收回利权运动'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-12', type: QuestionType.Multiple, question: '资产阶级革命派的骨干是一群资产阶级、小资产阶级知识分子,这个群体的出现与（ ）有关。', options: ['A.戊戌维新运动', 'B.取消科举制', 'C.举办新式学堂', 'D.自费或派遣留学生措施'], answer: ['C', 'D'] },
        { id: 'c3-m-13', type: QuestionType.Multiple, question: '20 世纪初期,以下在中国宣传资产阶级革命思想的人物有（ ）。', options: ['A.孙中山', 'B.章炳麟', 'C邹容', 'D.陈天华'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-14', type: QuestionType.Multiple, question: '20 世纪初资产阶级革命派和改良派围绕着（ ）展开了论战。', options: ['A.要不要以革命手段推翻君主专制', 'B.要不要实行共和', 'C.要不要社会革命', 'D.要不要保皇'], answer: ['A', 'B', 'C'] },
        { id: 'c3-m-15', type: QuestionType.Multiple, question: '下列（ ）组织是由孙中山亲自组建的。', options: ['A.光复会', 'B.同盟会', 'C.兴中会', 'D.中国国民党'], answer: ['B', 'C', 'D'] },
        { id: 'c3-m-16', type: QuestionType.Multiple, question: '1905 年,中国第一个资产阶级政党中国同盟会在东京成立,其政治纲领是（ ）。', options: ['A.驱除鞑虏', 'B.恢复中华', 'C.创立民国', 'D.平均地权'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-17', type: QuestionType.Multiple, question: '三民主义中“民族主义”的基本内容是（ ）。', options: ['A.驱逐鞑虏', 'B.恢复中华', 'C.平均地权', 'D.创立民国'], answer: ['A', 'B'] },
        { id: 'c3-m-18', type: QuestionType.Multiple, question: '孙中山先生是中国民主革命的伟大先驱，他的历史贡献体现在（ ）。', options: ['A.领导了革命', 'B.发动了以推翻北洋军阀统治为目标的北伐战争', 'C.重新解释三民主义并提出了联俄、联共、扶助农工三大政策', 'D.坚定维护民主共和制度'], answer: ['A', 'C', 'D'] },
        { id: 'c3-m-19', type: QuestionType.Multiple, question: '三民主义的局限性在于（ ）。', options: ['A.无明确的反帝纲领', 'B.忽略人民群众的作用', 'C.民权思想缺失', 'D.平均地权空想色彩浓郁'], answer: ['A', 'B'] },
        { id: 'c3-m-20', type: QuestionType.Multiple, question: '辛亥革命爆发的历史条件包括（ ）。', options: ['A.民族危机加剧', 'B.社会矛盾激化', 'C.清政府新政破产', 'D.资产阶级革命派壮大'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-21', type: QuestionType.Multiple, question: '南京临时政府成立后制定的法令政策措施有（ ）。', options: ['A.扫除种种封建弊端,保护人权', 'B.鼓励发展资本主义工商业', 'C.禁止种植和吸食鸦片', 'D.改革文化教育制度'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-22', type: QuestionType.Multiple, question: '《中华民国临时约法》规定由（ ）行使统治权。', options: ['A.参议院', 'B.临时大总统', 'C.国务员', 'D.法院'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c3-m-23', type: QuestionType.Multiple, question: '辛亥革命为中国民族资本主义的发展扫除了一些障碍，这是指（ ）。', options: ['A.辛亥革命推翻了阻碍民族资本主义发展的封建专制制度', 'B.南京临时政府颁布了一系列鼓励发展实业的法令，促进了民族资本主义发展', 'C.政治地位有了提高的实业家投资近代工业的热情被激发起来', 'D.辛亥革命促使帝国主义放松对华经济侵略'], answer: ['A', 'B', 'C'] }
    ]
  },
  {
    id: 'ch4',
    title: '第四章 中国共产党的成立和中国革命新局面',
    questions: [
        // 单选题 (29道)
        { id: 'c4-s-1', type: QuestionType.Single, question: '下列观点中，不属于新文化运动倡导者的观点的是( )。', options: ['A.提倡新道德，反对旧道德', 'B.中国的全部传统文化应该否定', 'C.提倡新文学，反对旧文学', 'D.封建礼教是“吃人的礼教”，其流毒“不减于洪水猛兽”'], answer: ['B'] },
        { id: 'c4-s-2', type: QuestionType.Single, question: '中国人是从( )开始真正了解马克思主义的。', options: ['A.新文化运动后', 'B.五四运动后', 'C.辛亥革命后', 'D.俄国十月革命后'], answer: ['D'] },
        { id: 'c4-s-3', type: QuestionType.Single, question: '（ ）是中国第一个传播马克思主义并主张向俄国十月革命学习的先进分子。', options: ['A.李大钊', 'B.陈独秀', 'C.鲁迅', 'D.胡适'], answer: ['A'] },
        { id: 'c4-s-4', type: QuestionType.Single, question: '标志中国新民主主义革命开端的事件是( )。', options: ['A.新文化运动', 'B.中国共产党的诞生', 'C.五四运动', 'D.辛亥革命'], answer: ['C'] },
        { id: 'c4-s-5', type: QuestionType.Single, question: '下列新文化运动倡导者中，不是早期马克思主义信仰者的是（ ）。', options: ['A.李大钊', 'B.毛泽东', 'C.胡适', 'D.蔡和森'], answer: ['C'] },
        { id: 'c4-s-6', type: QuestionType.Single, question: '李大钊成为中国的第一个马克思主义者的标志，是他于1919年9月、11月发表的文章( )。', options: ['A.《法俄革命之比较观》', 'B.《庶民的胜利》', 'C.《Bolshevism 的胜利》', 'D.《我的马克思主义观》'], answer: ['D'] },
        { id: 'c4-s-7', type: QuestionType.Single, question: '中国共产党历史上有“南陈北李，相约建党”的说法，其中“陈”、“李”分别指( )。', options: ['A.陈独秀和李达', 'B.陈独秀和李大钊', 'C.陈潭秋和李大钊', 'D.陈潭秋和李达'], answer: ['B'] },
        { id: 'c4-s-8', type: QuestionType.Single, question: '毛泽东认为，( )，是一个“开天辟地的大事变”。', options: ['A.十月革命', 'B.五四运动', 'C.中国共产党的成立', 'D.第一次国共合作'], answer: ['C'] },
        { id: 'c4-s-9', type: QuestionType.Single, question: '第一次国共合作正式形成的标志是( )。', options: ['A.中共一大', 'B.中共二大', 'C.中共三大', 'D.中国国民党第一次全国代表大会'], answer: ['D'] },
        { id: 'c4-s-10', type: QuestionType.Single, question: '国共合作之下进行的北伐所喊出的（ ）口号响彻大江南北。', options: ['A.外争国权，内惩国贼', 'B.打倒列强，除军阀', 'C.打土豪，分田地', 'D.停止内战，一致对外'], answer: ['B'] },
        { id: 'c4-s-11', type: QuestionType.Single, question: ' 新文化运动是从1915年9月陈独秀创办（ ）开始的。', options: ['A.《湘江评论》', 'B. 《青年杂志》', 'C. 《新民丛报》', 'D.《民报》'], answer: ['B'] },
        { id: 'c4-s-12', type: QuestionType.Single, question: '巴黎和会归还中国的是（ ）。', options: ['A.德国在山东获得的特权', 'B.香港', 'C.被德国掠去的天文仪器', 'D.取消二十一条'], answer: ['C'] },
        { id: 'c4-s-13', type: QuestionType.Single, question: ' 在五四运动前后的各种社会主义的思想中，（ ）思潮占着优势。', options: ['A. 无政府主义', 'B.社会民主主义', 'C. 工团主义', 'D.新村主义'], answer: ['A'] },
        { id: 'c4-s-14', type: QuestionType.Single, question: ' 中国工人阶级开始以独立的姿态登上历史舞台是在（ ）时期。', options: ['A.辛亥革命', 'B.五卅运动', 'C.五四运动', 'D.国共合作'], answer: ['C'] },
        { id: 'c4-s-15', type: QuestionType.Single, question: ' （ ）没有参加五四运动。', options: ['A. 工人阶级', 'B.小资产阶级', 'C.资产阶级', 'D.地主阶级'], answer: ['D'] },
        { id: 'c4-s-16', type: QuestionType.Single, question: '毛泽东读的三本书建立起他对马克思主义的信仰的书籍，（ ）不属于其中。', options: ['A.《资本论》', 'B.《共产党宣言》', 'C.《阶级斗争》', 'D.《社会主义史》'], answer: ['A'] },
        { id: 'c4-s-17', type: QuestionType.Single, question: ' 周恩来“定妥了我的目标”即共产主义是在（ ）。', options: ['A.1921 年', 'B.1920 年', 'C.1919 年', 'D.1922 年'], answer: ['B'] },
        { id: 'c4-s-18', type: QuestionType.Single, question: ' 中国工人阶级政党最早的组织，是在（ ）建立的。', options: ['A.北京', 'B.上海', 'C.长沙', 'D.济南'], answer: ['B'] },
        { id: 'c4-s-19', type: QuestionType.Single, question: ' 共产党早期组织领导的第一个工会是（ ）。', options: ['A.长辛店工人俱乐部（工会）', 'B.武汉工人协会', 'C.上海机器工会', 'D.广州工会'], answer: ['C'] },
        { id: 'c4-s-20', type: QuestionType.Single, question: ' 中国共产党成立之前的斗争之所以成效甚少，一个重要的原因，就在于未能（ ）。', options: ['A.充分地发动群众', 'B.理论联系实际', 'C.进行武装斗争', 'D.实事求是'], answer: ['A'] },
        { id: 'c4-s-21', type: QuestionType.Single, question: '不属于中国第一个工人运动高潮的是（ ）。', options: ['A. 香港海员罢工', 'B.京汉铁路工人罢工', 'C. 安源路矿工人罢工', 'D.五四工人大罢工'], answer: ['D'] },
        { id: 'c4-s-22', type: QuestionType.Single, question: '中国共产党成立后...中国共产党第一次独立领导并取得完全胜利的工人斗争是（ ）。', options: ['A. 京汉铁路工人罢工', 'B.香港海员罢工', 'C. 安源路矿工人罢工', 'D.开滦五矿工人罢工'], answer: ['C'] },
        { id: 'c4-s-23', type: QuestionType.Single, question: ' 中国第一个农民协会是在（ ）成立。', options: ['A.广东海丰县', 'B.浙江萧山县', 'C.湖南湘潭县', 'D.北京长辛店'], answer: ['B'] },
        { id: 'c4-s-24', type: QuestionType.Single, question: '（ ）实际上确定了联俄、联共、扶助农工三大革命政策。', options: ['A.中国共产党第一次全国代表大会', 'B.中国共产党第二次全国代表大会', 'C.国民党第一次全国代表大会', 'D.国民党第二次全国代表大会'], answer: ['C'] },
        { id: 'c4-s-25', type: QuestionType.Single, question: '中国共产党在（ ）上决定加入共产国际。', options: ['A.中国共产党第一次全国代表大会', 'B.中国共产党第二次全国代表大会', 'C.中国共产党第三次全国代表大会', 'D.中国共产党第四次全国代表大会'], answer: ['B'] },
        { id: 'c4-s-26', type: QuestionType.Single, question: '1915 年 9 月，陈独秀...此时陈独秀把主要注意力倾注于思想变革的原因是（ ）。', options: ['A.他认为批评时政不利于改造青年思想', 'B.他对资产阶级民主主义产生了怀疑', 'C.他对政治问题不感兴趣', 'D.他认定改造国民性是政治变革的前提'], answer: ['D'] },
        { id: 'c4-s-27', type: QuestionType.Single, question: '1914 年至 1918年的第一次世界大战...使中国的先进分子（ ）。', options: ['A.对西方资产阶级民主主义产生怀疑', 'B.对中国传统文化产生怀疑', 'C.认识到必须优先改造国民性', 'D.认识到工人阶级的重要作用'], answer: ['A'] },
        { id: 'c4-s-28', type: QuestionType.Single, question: '1918年12月，陈独秀在《每周评论》中说...1919年5月4日...又写道...导致陈独秀认识发生变化的直接原因是（ ）。', options: ['A.日本对德宣战，出兵山东', 'B.中国在巴黎和会上外交失败', 'C.苏俄宣布废除从前同中国签订的一切不平等条约', 'D.美国不愿放弃在华种种特权'], answer: ['B'] },
        { id: 'c4-s-29', type: QuestionType.Single, question: '新三民主义成为第一次国共合作的政治基础，究其原因，是由于新三民主义的政策（ ）。', options: ['A.同中国共产党在民主革命阶段的纲领基本一致', 'B.把斗争的矛头直接指向北洋军阀', 'C.体现了联俄、联共、扶助农工三大革命政策', 'D.把民主主义概括为“平均地权”'], answer: ['C'] },

        // 多选题 (25道)
        { id: 'c4-m-1', type: QuestionType.Multiple, question: '属于新文化运动倡导者观点的有（ ）。', options: ['A. “非孔学之小，实国学范围之大也。”', 'B. “孔子于其生存时代之社会，确足为其社会之中枢...”', 'C. “孔学优点，仆未尝不服膺”', 'D. “儒教不革命、儒学不转轮...何以造新国民？”'], answer: ['D'] },
        { id: 'c4-m-2', type: QuestionType.Multiple, question: '新文化运动的主阵地是( )。', options: ['A.民友社', 'B.《新青年》杂志', 'C.北京大学', 'D.政学会'], answer: ['B', 'C'] },
        { id: 'c4-m-3', type: QuestionType.Multiple, question: '新文化运动的基本口号是( )。', options: ['A.独立', 'B.富强', 'C.民主', 'D.科学'], answer: ['C', 'D'] },
        { id: 'c4-m-4', type: QuestionType.Multiple, question: '下列选项中，属于早期新文化运动主要内容的是( )。', options: ['A.提倡新文学，反对旧文学', 'B.提倡民主和科学，反对迷信和愚昧', 'C.提倡个性解放，反对封建礼教', 'D.主张实行文学革命'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-5', type: QuestionType.Multiple, question: '下列选项中，属于对早期新文化运动的正确认识的是( )。', options: ['A.在当时的社会环境中，要想从根本上改造国民...仅依靠少数人的呐喊是不可能的', 'B.新文化运动的倡导者们，回避反对军阀的斗争', 'C.新文化运动的参加者基本局限在知识分子的范围内', 'D.为中国人民提供一种正确认识中国国情的思想武器'], answer: ['A', 'B', 'C'] },
        { id: 'c4-m-6', type: QuestionType.Multiple, question: '“自竞争人权之说兴，机械资本之作广...此近世文明之缺点，无容讳言者也。”这句话表明了新文化运动的倡导者陈独秀对待资本主义的态度是( )。', options: ['A.某种程度的保留', 'B.对西方文化盲目崇拜', 'C.某种程度的怀疑', 'D.对资本主义完全失去信心'], answer: ['A', 'C'] },
        { id: 'c4-m-7', type: QuestionType.Multiple, question: '下列关于俄国十月革命的历史意义的正确说法有( )。', options: ['A.它是世界革命的新纪元', 'B.它是人类觉醒的新纪元', 'C.它昭示了资本主义制度并不是永恒的', 'D.它是一个具有划时代意义的世界性的历史事件'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-8', type: QuestionType.Multiple, question: '参加五四运动的社会阶级和阶层有( )。', options: ['A.工人阶级', 'B.农民阶级', 'C.小资产阶级', 'D.民族资产阶级'], answer: ['A', 'C', 'D'] },
        { id: 'c4-m-9', type: QuestionType.Multiple, question: '中国早期马克思主义思想运动的特点有( )。', options: ['A.重视对马克思主义基本理论的学习', 'B.明确地同第二国际的社会民主主义划清界限', 'C.注意从中国实际出发，学习、运用马克思主义的理论', 'D.开始提出知识分子应当同劳动群众相结合的思想'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-10', type: QuestionType.Multiple, question: '中国共产党早期组织的主要活动有( )。', options: ['A.研究和宣传马克思主义', 'B.同反马克思主义思潮展开论战', 'C.在工人中进行组织和宣传工作', 'D.成立社会主义青年团'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-11', type: QuestionType.Multiple, question: '下列属于对中共一大内容的描述不正确的有( )。', options: ['A.陈独秀作为代表出席大会，并被选为中央局书记', 'B.大会确定党的名称为中国共产党', 'C.大会确定了党的最高纲领和最低纲领', 'D.正式宣告了中国共产党的成立'], answer: ['A', 'C'] },
        { id: 'c4-m-12', type: QuestionType.Multiple, question: '下列各项活动为中国共产党的诞生创造条件的有( )。', options: ['A.马克思主义在中国的广泛传播', 'B.中国工人阶级的成长、壮大；工人运动的发展及其水平的提高', 'C.党的早期组织的成立', 'D.一批具有初步共产主义思想的知识分子的日益成熟'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-13', type: QuestionType.Multiple, question: '中共二大通过的民主革命纲领的内容包括( )。', options: ['A.实现社会主义、共产主义', 'B.打倒军阀', 'C.推翻国际帝国主义的压迫', 'D.统一中国为真正民主共和国'], answer: ['B', 'C', 'D'] },
        { id: 'c4-m-14', type: QuestionType.Multiple, question: '下列事件中，由蒋介石亲手制造的有( )。', options: ['A.中山舰事件', 'B.四·一二反革命政变', 'C.马日事变', 'D.七·一五反革命政变'], answer: ['A', 'B'] },
        { id: 'c4-m-15', type: QuestionType.Multiple, question: ' 十月革命以后、五四运动前后...各种思潮被当做社会主义介绍到中国，包括（ ）等。', options: ['A.无政府主义', 'B.工团主义', 'C.基尔特（行会）社会主义', 'D.社会民主主义'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-16', type: QuestionType.Multiple, question: ' 五四运动的爆发的时代条件有（ ）。', options: ['A.新的社会力量的成长、壮大', 'B.新文化运动掀起的思想解放的潮流', 'C.马克思主义的传播', 'D.俄国十月革命对中国的影响'], answer: ['A', 'B', 'D'] },
        { id: 'c4-m-17', type: QuestionType.Multiple, question: '《新青年》的主要撰稿人有（ ）。', options: ['A. 李大钊', 'B.鲁迅', 'C.胡适', 'D.梁启超'], answer: ['A', 'B', 'C'] },
        { id: 'c4-m-18', type: QuestionType.Multiple, question: ' 五四运动的直接斗争目标是（ ）。', options: ['A.罢免亲日派官僚的职务', 'B.推翻北洋政府统治', 'C.拒绝巴黎和约签字', 'D.取消二十一条'], answer: ['A', 'C'] },
        { id: 'c4-m-19', type: QuestionType.Multiple, question: ' 早期马克思主义思想运动的特点有（ ）。', options: ['A.重视对马克思主义基本理论的学习', 'B.注意从中国的实际岀发，学习、运用马克思主义理论', 'C.提出反对帝国主义', 'D.开始提出知识分子应当同劳动群众相结合的思想'], answer: ['A', 'B', 'D'] },
        { id: 'c4-m-20', type: QuestionType.Multiple, question: '各地共产党的早期组织创办了一批专门供工人阅读的进行马克思主义启蒙教育的刊物，包括（ ）。', options: ['A. 《劳动界》', 'B.《劳动音》', 'C.《工人月刊》', 'D.《济南劳动月刊》'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-21', type: QuestionType.Multiple, question: ' 中国共产党人的初心和使命是（ ）。', options: ['A.为中国人民谋幸福', 'B.为中华民族谋复兴', 'C.为人民解放', 'D.为民族独立'], answer: ['A', 'B'] },
        { id: 'c4-m-22', type: QuestionType.Multiple, question: ' 中国共产党的先驱们创建了中国共产党，形成了（ ）的伟大建党精神，这是中国共产党的精神之源。', options: ['A.坚持真理、坚守理想', 'B.践行初心、担当使命', 'C.不怕牺牲、英勇斗争', 'D.对党忠诚、不负人民'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-23', type: QuestionType.Multiple, question: ' 中国共产党的成立,深刻改变了（ ）。', options: ['A.近代以后中华民族发展的方向和进程', 'B.中国人民的前途和命运', 'C.世界发展的趋势和格局', 'D.中华民族的前途和命运'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c4-m-24', type: QuestionType.Multiple, question: '新文化运动的历史意义表现在（ ）。', options: ['A.是中国历史上一次前所未有的启蒙运动', 'B.在社会上掀起了一股思想解放的潮流', 'C.为马克思主义在中国的传播创造了有利条件', 'D.彻底否定了孔学的历史作用'], answer: ['A', 'B', 'C'] },
        { id: 'c4-m-25', type: QuestionType.Multiple, question: '大革命规模宏伟，内涵丰富。与辛亥革命相比较，其不同点在于（ ）。', options: ['A.它的主要斗争形式是武装斗争', 'B.它广泛而深刻地发动了工农群众', 'C.它的革命对象是帝国主义和封建军阀', 'D.它是在以国共合作为基础的统一战线的组织形式下进行的'], answer: ['B', 'C', 'D'] }
    ]
  },
  {
    id: 'ch5',
    title: '第五章 中国革命的新道路',
    questions: [
        // 单选题 (28道)
        { id: 'c5-s-1', type: QuestionType.Single, question: '1928 年，国民党政府军队继续北伐，（ ）首领张作霖在退回关外途中，被日本人预埋的炸药炸死。', options: ['A.直系', 'B.皖系', 'C.奉系', 'D.桂系'], answer: ['C'] },
        { id: 'c5-s-2', type: QuestionType.Single, question: '（ ）于1928年12月29日从东北发出通告，宣布“遵守三民主义，服从国民政府，改易旗帜”。', options: ['A.蒋介石', 'B.张学良', 'C.胡汉民', 'D.张作霖'], answer: ['B'] },
        { id: 'c5-s-3', type: QuestionType.Single, question: '为了控制人民，禁止革命活动，国民党大力推行（ ），“共具联保连坐切结”。', options: ['A.保安队', 'B.特务系统', 'C.保甲制度', 'D.审查制度'], answer: ['C'] },
        { id: 'c5-s-4', type: QuestionType.Single, question: '（ ）打响了武装反抗国民党反动统治的第一枪。这是中国共产党独立领导革命战争、创建人民军队和武装夺取政权的开端。', options: ['A.武昌起义', 'B.南昌起义', 'C.秋收起义', 'D.广州起义'], answer: ['B'] },
        { id: 'c5-s-5', type: QuestionType.Single, question: '毛泽东在八七会议上提出( )。', options: ['A.须知政权是由枪杆子中取得的', 'B.没有文化的军队是一支愚蠢的军队', 'C.没有调查就没有发言权', 'D.帝国主义和一切反动派都是纸老虎'], answer: ['A'] },
        { id: 'c5-s-6', type: QuestionType.Single, question: '（ ）确立了党的“开展土地革命和武装反抗国民党反动派”的总方针。', options: ['A.八七会议', 'B.古田会议', 'C.遵义会议', 'D.瓦窑堡会议'], answer: ['A'] },
        { id: 'c5-s-7', type: QuestionType.Single, question: '毛泽东率领的秋收起义部队转移到（ ）地区，创建了农村革命根据地。', options: ['A.赣南', 'B.湘南', 'C.海陆丰', 'D.井冈山'], answer: ['D'] },
        { id: 'c5-s-8', type: QuestionType.Single, question: '1929 年 12 月，（ ）决议案确立了思想建党、政治建军原则。', options: ['A.八七会议', 'B.古田会议', 'C.遵义会议', 'D.瓦窑堡会议'], answer: ['B'] },
        { id: 'c5-s-9', type: QuestionType.Single, question: '毛泽东在《反对本本主义》中提出的著名科学论断是( )', options: ['A.枪杆子里面出政权', 'B.没有文化的军队是一支愚蠢的军队', 'C.没有调查就没有发言权', 'D.帝国主义和一切反动派都是纸老虎'], answer: ['C'] },
        { id: 'c5-s-10', type: QuestionType.Single, question: '1931 年 11 月，中华苏维埃第一次全国代表大会在江西瑞金举行，成立了中华苏维埃共和国临时中央政府，（ ）当选为主席。', options: ['A.瞿秋白', 'B.张闻天', 'C.周恩来', 'D.毛泽东'], answer: ['D'] },
        { id: 'c5-s-11', type: QuestionType.Single, question: '从 1927 年7月大革命失败到1935年1月遵义会议召开之前，“左”倾错误先后（ ）在党中央的领导机关取得统治地位。', options: ['A.两次', 'B.三次', 'C.四次', 'D.五次'], answer: ['B'] },
        { id: 'c5-s-12', type: QuestionType.Single, question: '王明等人的“左”倾教条主义错误，对中国革命造成了极其严重的危害，其最大的恶果，是（ ）', options: ['A.压制党内民主，对坚持正确意见的同志“残酷斗争”“无情打击”', 'B.召开赣南会议，剥夺毛泽东对中央根据地红军的领导权', 'C.白区党的工作遭到严重破坏，临时中央政治局无法在上海立足，被迫迁到中央根据地', 'D.红军在第五次反“围剿”作战中遭到失败，实行战略转移'], answer: ['D'] },
        { id: 'c5-s-13', type: QuestionType.Single, question: '中央红军主力开始长征后，（ ）等率领中央根据地留下的部分红军在南方坚持进行艰苦的游击战争。', options: ['A.陈毅、周恩来', 'B.项英、陈毅', 'C.项英、朱德', 'D.朱德、陈毅'], answer: ['B'] },
        { id: 'c5-s-14', type: QuestionType.Single, question: '1935 年，在长征途中召开的（ ）在极其危急的情况下挽救了中国共产党...成为中国共产党历史上一的生死悠关的转折点。', options: ['A.八七会议', 'B.古田会议', 'C.遵义会议', 'D.瓦窑堡会议'], answer: ['C'] },
        { id: 'c5-s-15', type: QuestionType.Single, question: '遵义会议决定，由（ ）代替博古负总的责任，并成立了新的“三人团”全权负责红军的军事行动。', options: ['A.李徳', 'B.张闻天', 'C.周恩来', 'D.王稼祥'], answer: ['B'] },
        { id: 'c5-s-16', type: QuestionType.Single, question: '中国工农红军的（ ）是一部伟大的革命英雄主义的史诗。', options: ['A.反围剿', 'B.长征', 'C.抗战', 'D.根据地建设'], answer: ['B'] },
        { id: 'c5-s-17', type: QuestionType.Single, question: '下列不属于长征中发生的是（ ）。', options: ['A.四渡赤水河', 'B.长沙保卫战', 'C.抢渡大渡河', 'D.翻越夹金山'], answer: ['B'] },
        { id: 'c5-s-18', type: QuestionType.Single, question: '长征途中，中共中央同红四方面军领导人（ ）分裂中央、分裂红军的严重错误进行了坚决的斗争。', options: ['A.博古', 'B.李立三', 'C.王明', 'D.张国焘'], answer: ['D'] },
        { id: 'c5-s-19', type: QuestionType.Single, question: '1936 年 10 月，红二、四方面军先后同红一方面军在（ ）、静宁将台堡会师。至此，三大主力红军的长征胜利结束。', options: ['A.陕北吴起镇', 'B.延安', 'C.甘肃会宁', 'D.甘泉地区'], answer: ['C'] },
        { id: 'c5-s-20', type: QuestionType.Single, question: '2016 年 10 月21日，习近平在纪念红军长征胜利（ ）周年大会上发表重要讲话称，这一惊天动地的革命壮举，是中国共产党和红军谱写的壮丽史诗...', options: ['A.60', 'B.70', 'C.80', 'D.90'], answer: ['C'] },
        { id: 'c5-s-21', type: QuestionType.Single, question: '1927 年大革命失败后，党的工作重心开始转向农村...农村革命根据地能够在中国长期存在和发展的根本原因是（ ）。', options: ['A.中国是一个政治、经济、文化发展极不平衡的半殖民地半封建的大国', 'B.良好的群众基础和革命形势的继续向前发展', 'C.相当力量正式红军的存在', 'D.党的领导及其正确的政策'], answer: ['A'] },
        { id: 'c5-s-22', type: QuestionType.Single, question: '1929 年 12 月下旬，红四军党的第九次代表大会...通过了著名的古田会议决议。决议的中心思想是（ ）。', options: ['A.武装斗争是中国革命的主要形式', 'B.中国共产党必须服从共产国际的领导', 'C.用无产阶级思想进行军队和党的建设', 'D.在农村根据地广泛开展土地革命'], answer: ['C'] },
        { id: 'c5-s-23', type: QuestionType.Single, question: '中国共产党在领导人民革命的过程中...武装斗争就是中国共产党在中国革命中战胜敌人的重要法宝之一，其实质是（ ）。', options: ['A.无产阶级领导的反帝国主义战争', 'B.资产阶级领导的反封建战争', 'C.工农联合的反军阀战争', 'D.工人阶级领导的农民战争'], answer: ['D'] },
        { id: 'c5-s-24', type: QuestionType.Single, question: '在实践上把中国革命重心从城市转入农村的事件是( )。', options: ['A.南昌起义', 'B.土地革命', 'C.秋收起义', 'D.广州起义'], answer: ['C'] },
        { id: 'c5-s-25', type: QuestionType.Single, question: '通过三大起义，共产党人认识到的重要问题是：( )。', options: ['A.必须武装反抗国民党反动派', 'B.建立革命政权的重要性', 'C.建立革命武装的重要性.', 'D.中国革命必须从城市转入农村'], answer: ['D'] },
        { id: 'c5-s-26', type: QuestionType.Single, question: '毛泽东建立农村革命根据地，走农村包围城市道路的主要依据是：( )。', options: ['A.“八七会议”精神', 'B.共产国际指示', 'C.中国的国情', 'D.人民群众的支持'], answer: ['C'] },
        { id: 'c5-s-27', type: QuestionType.Single, question: '革命根据地迅速发展的主要原因是：( )。', options: ['A.中共的正确领导', 'B.开展了土地革命', 'C.得到了人民的支持', 'D.根据地进行了经济建设'], answer: ['B'] },
        { id: 'c5-s-28', type: QuestionType.Single, question: '毛泽东等开辟农村革命根据地，走农村包围城市道路，主要体现的唯物主义原理是：( )', options: ['A.一切从实际出发', 'B.走群众路线', 'C.矛盾的普遍性和特殊性', 'D.具体问题具体分析'], answer: ['A'] },

        // 多选题 (21道)
        { id: 'c5-m-1', type: QuestionType.Multiple, question: '1927 年七一五政变以后，一段时间内，国民党的（ ）和（ ）仍然互相对峙。经过几番周折，实现了宁、汉合流。', options: ['A.南京国民政府', 'B.武汉国民政府', 'C.北京政府', 'D.广州国民政府'], answer: ['A', 'B'] },
        { id: 'c5-m-2', type: QuestionType.Multiple, question: '在1927 年大革命失败以后，国民党...变成了一个由代表（ ）利益的反动集团所控制的政党。', options: ['A.地主阶级', 'B.民主分子', 'C.买办性的大资产阶级', 'D.知识分子'], answer: ['A', 'C'] },
        { id: 'c5-m-3', type: QuestionType.Multiple, question: '为了镇压人民和消灭异己力量，国民党建立了庞大的全国性特务系统。如（ ）。', options: ['A.上海特工总部', 'B.保安队', 'C.国民党中央组织部调查统计局', 'D.国民党军事委员会调查统计局'], answer: ['C', 'D'] },
        { id: 'c5-m-4', type: QuestionType.Multiple, question: '1927 年 8月7日，中共中央在汉口秘密召开紧急会议（即八七会议），这次会议（ ）。', options: ['A.彻底清算了大革命后期的陈独秀右倾机会主义错误', 'B.确定了土地革命和武装反抗国民党反动统治的总方针', 'C.选出了以瞿秋白为首的中央临时政治局', 'D.确立了党对军队的绝对领导原则'], answer: ['A', 'B', 'C'] },
        { id: 'c5-m-5', type: QuestionType.Multiple, question: '革命失败，得了惨痛的教训...中国革命由此发展到了一个新的阶段，即（ ）。', options: ['A.国民革命时期', 'B.土地革命战争时期', 'C.十年内战时期', 'D.解放战争时期'], answer: ['B', 'C'] },
        { id: 'c5-m-6', type: QuestionType.Multiple, question: '毛泽东1928—1930年期间论述农村包围城市、武装夺取政权革命道路的主要著作是( )。', options: ['A.《中国社会各阶级的分析》', 'B.《中国的红色政权为什么能够存在》', 'C.《星星之火，可以燎原》', 'D.《井冈山的斗争》'], answer: ['B', 'C', 'D'] },
        { id: 'c5-m-7', type: QuestionType.Multiple, question: '毛泽东在《中国的红色政权为什么能够存在？》和《井冈山的斗争》两篇文章中科学阐述了（ ）的辩证统一关系。', options: ['A.土地革命', 'B.武装斗争', 'C.党的建设', 'D.根据地建设'], answer: ['A', 'B', 'D'] },
        { id: 'c5-m-8', type: QuestionType.Multiple, question: '1929 年 12 月下旬，红四军党的第九次代表大会在福建上杭县古田村召开，会议（ ）。', options: ['A.创造性地解决了在农村环境中如何加强思想建设，建设党领导的人民军队的问题', 'B.通过决议规定红军必须绝对服从共产党的领导', 'C.对于中国革命新道路的开辟和坚持具有重要意义', 'D.确定农村工作是第一步，城市工作是第二步'], answer: ['A', 'B', 'C'] },
        { id: 'c5-m-9', type: QuestionType.Multiple, question: '土地革命战争时期，中国共产党在中国历史上第一个制定了可以付诸实践的比较完整的土地革命纲领和路线，其阶级路线是（ ）。', options: ['A.坚定地依靠贫农、雇农，联合中农，限制富农', 'B.保护工商业者，团结地主阶级', 'C.团结知识分子', 'D.保护中小工商业者，消灭地主阶级'], answer: ['A', 'D'] },
        { id: 'c5-m-10', type: QuestionType.Multiple, question: '土地革命战争时期，国民党统治区的共产党人和进步文化界人士在文化战线开展斗争，形成了声势浩大的左翼文化运动，其中（ ）等作品都在群众中产生了广泛而深刻的影响。', options: ['A.鲁迅的杂文', 'B.瞿秋白的评论', 'C.茅盾的小说《子夜》', 'D.邹韬奋主办的《生活周刊》'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c5-m-11', type: QuestionType.Multiple, question: '1931 年 1 月至1935年1月以陈绍禹（王明）为代表的“左”倾教条主义，其主要错误有（ ）。', options: ['A.认为革命形势在不断高涨，盲目要求“创造总暴动的局面”', 'B.混淆民主革命与社会主义革命的界限', 'C.继续坚持以城市为中心', 'D.进攻中的冒险主义、防御中的保守主义、退却中的逃跑主义'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c5-m-12', type: QuestionType.Multiple, question: '遵义会议开始确立以毛泽东为主要代表的马克思主义的正确路线在党中央的领导地位，集中解决了当时具有决定意义的 ( )。', options: ['A.军事问题', 'B.组织问题', 'C.政治问题', 'D.思想路线问题'], answer: ['A', 'B'] },
        { id: 'c5-m-13', type: QuestionType.Multiple, question: '在 20 世纪30年代前期、中期，中国共产党内屡犯“左”倾错误的多方面原因是 ( )', options: ['A.八七会议后党内存在着浓重的“左”倾情绪', 'B.共产国际对中共党内事务的错误干预和瞎指挥', 'C.对共产国际百分之百的忠诚，是中国革命走向胜利的唯一保证', 'D.不善于把马克思列宁主义与中国实际全面地、正确地结合起来'], answer: ['A', 'B', 'D'] },
        { id: 'c5-m-14', type: QuestionType.Multiple, question: '在大革命失败后的白色恐怖下，( )等人都毅然加入了中国共产党。', options: ['A.郭沫若', 'B.徐特立', 'C.贺龙', 'D.彭德怀'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c5-m-15', type: QuestionType.Multiple, question: '下列说法正确的有（ ）', options: ['A.1931 年中华苏维埃第一次全国代表大会通过了《中华苏维埃共和国宪法大纲》', 'B.中华苏维埃共和国实行工农兵代表大会制度', 'C.中华苏维埃共和国主席为张闻天，首都为江西瑞金', 'D.苏维埃政府坚决开展反对贪污腐化等的斗争，规定“贪污公款在500元以上者处以死刑”'], answer: ['A', 'B', 'D'] },
        { id: 'c5-m-16', type: QuestionType.Multiple, question: '1927 年 10 月，毛泽东率领湘赣边界秋收起义的工农革命军，开始创建以宁冈为中心的井冈山革命根据地。毛泽东确定在井冈山建立根据地，是因为这个地区（ ）。', options: ['A.有较好的群众基础', 'B.地势险要且易守难攻', 'C.易于部队筹款筹粮', 'D.敌人的统治力量比较薄弱'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c5-m-17', type: QuestionType.Multiple, question: '忠诚于党、听党指挥是我军的光荣传统。1929年12月下旬...规定红军是一个执行革命的政治任务的武装集团，必须（ ）。', options: ['A.实行全国军事的总动员', 'B.担负打仗、筹款和做群众工作的任务', 'C.加强政治工作', 'D.绝对服从共产党的领导'], answer: ['B', 'C', 'D'] },
        { id: 'c5-m-18', type: QuestionType.Multiple, question: '标志着中国共产党进入了创造红军的新时期的起义有（ ）。', options: ['A.秋收起义', 'B.广州起义', 'C.百色起义', 'D.南昌起义'], answer: ['A', 'B', 'D'] },
        { id: 'c5-m-19', type: QuestionType.Multiple, question: '1927 年，毛泽东率领秋收起义部队进军井冈山途中进行了著名的三湾改编，其主要内容有：（ ）。', options: ['A.将一个师缩编为一个团', 'B.决定将共产党支部建在连上', 'C.规定了红军的三大任务', 'D.规定在部队内部实行民主管理'], answer: ['A', 'B', 'D'] },
        { id: 'c5-m-20', type: QuestionType.Multiple, question: '土地革命战争时期，中国的红色政权能够存在和发展的客观条件有：（ ）。', options: ['A.政治经济发展的不平衡', 'B.相当力量的正式红军存在', 'C.第一次国内革命战争的影响', 'D.全国革命形势的继续向前发展'], answer: ['A', 'C', 'D'] },
        { id: 'c5-m-21', type: QuestionType.Multiple, question: '1927 年大革命失败后，与共产党进行斗争的同时，积极从事反蒋民主斗争的还有:（ ）。', options: ['A.以宋庆龄为代表的爱国民主力量', 'B.以邓演达为首的第三党', 'C.汪精卫为首的改组派', 'D.以胡汉民为首的两广实力派'], answer: ['A', 'B', 'C', 'D'] }
    ]
  },
  {
    id: 'ch6',
    title: '第六章 中华民族的抗日战争',
    questions: [
        // 单选题 (56道)
        { id: 'c6-s-1', type: QuestionType.Single, question: '20世纪（），日本和德国、意大利分别在世界的东方和西方形成战争策源地。', options: ['A.20年代', 'B.30年代', 'C.40年代', 'D.50年代'], answer: ['B'] },
        { id: 'c6-s-2', type: QuestionType.Single, question: '（）以后，日本开始走上资本主义道路，逐渐发展成为军国主义国家。', options: ['A.德川幕府', 'B.明治维新', 'C.黑船事件', 'D.洋务运动'], answer: ['B'] },
        { id: 'c6-s-3', type: QuestionType.Single, question: '1927年，日本首相主持召开“东方会议”，宣示了《对华政策纲要》，企图把“（）”从中国本土彻底分割出去，并决心为之诉诸武力。', options: ['A.满蒙', 'B.东北', 'C.台湾', 'D.澎湖列岛'], answer: ['A'] },
        { id: 'c6-s-4', type: QuestionType.Single, question: '（）9月18日深夜，日本关东军炸毁“南满铁路”沈阳北郊柳条湖附近的一段路轨，反诬中国军队所为，炮轰东北军驻地北大营，接着向沈阳等地发动进攻。', options: ['A.1930年', 'B.1931年', 'C.1932年', 'D.1937年'], answer: ['B'] },
        { id: 'c6-s-5', type: QuestionType.Single, question: '至（）2月，中国东北全境沦陷。', options: ['A.1930年', 'B.1931年', 'C.1932年', 'D.1937年'], answer: ['C'] },
        { id: 'c6-s-6', type: QuestionType.Single, question: '国民党政府对日本的侵略采取妥协退让方针，（）在1931年7月提出“攘外必先安内”的方针。', options: ['A.蒋介石', 'B.张学良', 'C.宋子文', 'D.何应钦'], answer: ['A'] },
        { id: 'c6-s-7', type: QuestionType.Single, question: '（），日本在华北制造一系列事端，又策动华北五省两市“防共自治运动”，制造傀儡政权，即华北事变。', options: ['A.1931年', 'B.1932年', 'C.1935年', 'D.1937年'], answer: ['C'] },
        { id: 'c6-s-8', type: QuestionType.Single, question: '( )标志着日本全面侵华战争的开始。', options: ['A.九一八事变', 'B.华北事变', 'C.卢沟桥事变', 'D.一二八事变'], answer: ['C'] },
        { id: 'c6-s-9', type: QuestionType.Single, question: '( )标志着日本变中国为其独占殖民地的阶段由此开始。', options: ['A.九一八事变', 'B.华北事变', 'C.卢沟桥事变', 'D.一二八事变'], answer: ['A'] },
        { id: 'c6-s-10', type: QuestionType.Single, question: '1932年4月15日，（）宣布对日作战。', options: ['A.东北抗日联军', 'B.中华苏维埃共和国临时中央政府', 'C.东北军', 'D.国民政府'], answer: ['B'] },
        { id: 'c6-s-11', type: QuestionType.Single, question: '1944年4月至1945年1月的( )中，国民党军队大溃败。', options: ['A.淞沪会战', 'B.豫湘桂战役', 'C.南昌战役', 'D.武汉会战'], answer: ['B'] },
        { id: 'c6-s-12', type: QuestionType.Single, question: '早在（）签订后，日本就开始了在台湾长达50年的殖民统治。', options: ['A.《天津条约》', 'B.《北京条约》', 'C.《马关条约》', 'D.《辛丑条约》'], answer: ['C'] },
        { id: 'c6-s-13', type: QuestionType.Single, question: '至（）2月，中国东北全境沦陷。', options: ['A.1931年', 'B.1932年', 'C.1935年', 'D.1937年'], answer: ['B'] },
        { id: 'c6-s-14', type: QuestionType.Single, question: '（）12月，日军占领中国国民政府首都南京后，制造了震惊中外的“南京大屠杀”。', options: ['A.1937年', 'B.1938年', 'C.1939年', 'D.1940年'], answer: ['A'] },
        { id: 'c6-s-15', type: QuestionType.Single, question: '在（）后，面对日本的野蛮侵略，中国人民毅然奋起、英勇抵抗，进行了长达（）年艰苦卓绝的抗日战争。', options: ['A、九一八事变 十四', 'B、九一八事变 八', 'C、七七事变 十四', 'D、七七事变 八'], answer: ['A'] },
        { id: 'c6-s-16', type: QuestionType.Single, question: '1932 年一·二八事变后，国民党（ ）奋起抗日。', options: ['A.第十九路军', 'B.西北军', 'C.东北军', 'D.北路军'], answer: ['A'] },
        { id: 'c6-s-17', type: QuestionType.Single, question: '1935 年底，北平学生举行声势浩大的抗日游行...这就是（ ）。', options: ['A.五四运动', 'B.一·二八事变', 'C.一二·九运动', 'D. 二·二八事件'], answer: ['C'] },
        { id: 'c6-s-18', type: QuestionType.Single, question: '1935 年 12 月，中共中央在陕北（ ）召开政治局扩大会议，提出党的基本策略任务是建立广泛的抗日民族统一战线。', options: ['A.延安', 'B.瓦窑堡', 'C.西安', 'D.遵义'], answer: ['B'] },
        { id: 'c6-s-19', type: QuestionType.Single, question: '（ ）12 月，爱国将领张学良、杨虎城为实现停止内战、共同抗日，对蒋介石实行“兵谏”。', options: ['A.1931 年', 'B.1936年', 'C.1937 年', 'D.1938 年'], answer: ['B'] },
        { id: 'c6-s-20', type: QuestionType.Single, question: '（ ）和平解决成为时局转换的枢纽，十年内战的局面基本结束，国内和平初步实现。', options: ['A.福建事变', 'B.卢沟桥事变', 'C.华北事变', 'D.西安事变'], answer: ['D'] },
        { id: 'c6-s-21', type: QuestionType.Single, question: '1937 年9月...以国共两党第二次合作为基础的（ ）正式形成。', options: ['A.国共统一战线', 'B.抗日民族统一战线', 'C.工农民主统一战线', 'D.爱国统一战线'], answer: ['B'] },
        { id: 'c6-s-22', type: QuestionType.Single, question: '1937 年 8 月，中共中央革命军事委员会发布命令，宣布红军改编为（ ）。', options: ['A.国民革命军第八路军', 'B.国民革命军新编第四军', 'C.东北抗日联军', 'D.抗日义勇军'], answer: ['A'] },
        { id: 'c6-s-23', type: QuestionType.Single, question: '1933 年 5 月，原西北军将领（ ）在张家口成立察哈尔民众抗日同盟军。', options: ['A.蔡廷锴', 'B.蒋光鼐', 'C.冯玉祥', 'D.吉鸿昌'], answer: ['C'] },
        { id: 'c6-s-24', type: QuestionType.Single, question: '1933 年 11 月，国民党第十九路军将领蔡廷锴、蒋光鼐以及国民党内爱国人士李济深、陈铭枢等发动反蒋抗日事变，即（ ）。', options: ['A.华北事变', 'B.西安事变', 'C.福州事变', 'D.福建事变'], answer: ['D'] },
        { id: 'c6-s-25', type: QuestionType.Single, question: '1938 年，（ ）等部进行了台儿庄战役，取得大捷。', options: ['A.冯玉祥', 'B.李宗仁', 'C.佟麟阁', 'D.陈诚'], answer: ['B'] },
        { id: 'c6-s-26', type: QuestionType.Single, question: '在（ ）会战中，谢晋元率孤军据守四行仓库，被誉为“八百壮士”。', options: ['A.武汉会战', 'B.太原会战', 'C.淞沪会战', 'D.长沙会战'], answer: ['C'] },
        { id: 'c6-s-27', type: QuestionType.Single, question: '在抗战初期，国民政府实行过若干有利于抗战的政策，1938年6月，（ ）成立。', options: ['A.全国各界救国联合会', 'B.国民参政会', 'C.抗日民主政权', 'D.边区参议会'], answer: ['B'] },
        { id: 'c6-s-28', type: QuestionType.Single, question: '1938 年初，国民政府改组军事委员会，下设政治部，聘请（ ）担任政治部副部长。', options: ['A.周恩来', 'B.郭沫若', 'C.李宗仁', 'D.陈诚'], answer: ['A'] },
        { id: 'c6-s-29', type: QuestionType.Single, question: '1940 年，在（ ）中，第三十三集团军总司令张自忠将军在激战中殉国。', options: ['A.武汉会战', 'B.长沙会战', 'C.枣宜会战', 'D.豫湘桂会战'], answer: ['C'] },
        { id: 'c6-s-30', type: QuestionType.Single, question: '1942 年，中国远征军进入缅甸对日作战。陆军第二零零师师长（ ）在缅北殉国。', options: ['A.佟麟阁', 'B.孙立人', 'C.张自忠', 'D.戴安澜'], answer: ['D'] },
        { id: 'c6-s-31', type: QuestionType.Single, question: '（ ）大溃败成为大后方人心变动的重要转折点，越来越多的人对国民党统治集团失去了信任。', options: ['A.南京', 'B.武汉', 'C.豫湘桂', 'D.淞沪'], answer: ['C'] },
        { id: 'c6-s-32', type: QuestionType.Single, question: '1937 年 8 月，中国共产党在陕北（ ）召开政治局扩大会议，制定了抗日救国十大纲领...', options: ['A.洛川', 'B.瓦窑堡', 'C.延安', 'D.西柏坡'], answer: ['A'] },
        { id: 'c6-s-33', type: QuestionType.Single, question: '1938 年 5 月至6月间，毛泽东发表（ ）的讲演...系统阐明了持久抗战的总方针。', options: ['A.《论联合政府》', 'B.《论持久战》', 'C.《抗日游击战争的战略问题》', 'D.《中国革命和中国共产党》'], answer: ['B'] },
        { id: 'c6-s-34', type: QuestionType.Single, question: '1937 年，八路军取得( )，打破了日军不可战胜的神话。', options: ['A.台儿庄战役', 'B.平型关大捷', 'C.百团大战', 'D.忻口会战'], answer: ['B'] },
        { id: 'c6-s-35', type: QuestionType.Single, question: '1940 年8月至翌年1月，八路军总部在华北发动了一次大规模的对日军的进攻，即（ ）。', options: ['A.台儿庄战役', 'B.平型关大捷', 'C.百团大战', 'D.忻口会战'], answer: ['C'] },
        { id: 'c6-s-36', type: QuestionType.Single, question: '1941 年 1 月，国民党顽固派发动第二次反共高潮，制造了（ ）。', options: ['A.福建事变', 'B. 马日事变', 'C.八一三事变', 'D.皖南事变'], answer: ['D'] },
        { id: 'c6-s-37', type: QuestionType.Single, question: '1941 年 5 月，中共中央批准颁布的《（ ）施政纲领》，全面地体现了中国共产党关于根据地建设的基本方针。', options: ['A.陕甘宁边区', 'B. 鄂豫皖边区', 'C.晋察冀边区', 'D. 湘赣边区'], answer: ['A'] },
        { id: 'c6-s-38', type: QuestionType.Single, question: '抗日民主政权实行各民族平等团结、共同抗日的基本政策，在少数民族聚居地区试行（ ）。', options: ['A.民主集中制', 'B. “三三制”', 'C.民族区域自治', 'D. 基层群众自治'], answer: ['C'] },
        { id: 'c6-s-39', type: QuestionType.Single, question: '为了克服根据地面临的严重困难局面，毛泽东发出了“自己动手，丰衣足食”的号召，中国共产党领导根据地军民开展了（ ）。', options: ['A.大生产运动', 'B. 改造二流子运动', 'C.普选运动', 'D. 减租减息运动'], answer: ['A'] },
        { id: 'c6-s-40', type: QuestionType.Single, question: '八路军第三五九旅艰苦奋斗，使（ ）变成了“陕北江南”。', options: ['A.新疆', 'B.南泥湾', 'C.西柏坡', 'D.延安'], answer: ['B'] },
        { id: 'c6-s-41', type: QuestionType.Single, question: '全民族抗战开始后，中共中央所在地（ ）成了革命者向往的“圣地”。', options: ['A.瑞金', 'B. 延安', 'C.西柏坡', 'D. 西安'], answer: ['B'] },
        { id: 'c6-s-42', type: QuestionType.Single, question: '抗战时期...1939年1月后，由中共中央（ ）具体领导对国民党统治区的工作。', options: ['A.书记处', 'B. 中央局', 'C.东北局', 'D. 南方局'], answer: ['D'] },
        { id: 'c6-s-43', type: QuestionType.Single, question: '1944 年 9 月，中共参政员（ ）在国民参政会上正式提出立即结束国民党一党统治、建立各抗日党派民主联合政府的主张...', options: ['A.黄炎培', 'B. 陈嘉庚', 'C.李鼎铭', 'D. 林伯渠'], answer: ['D'] },
        { id: 'c6-s-44', type: QuestionType.Single, question: '在中国共产党的历史上，第一次鲜明地提出“马克思主义中国化”命题和任务的会议是( )', options: ['A.中共二大', 'B.遵义会议', 'C.中共六届六中全会', 'D.中共七大'], answer: ['C'] },
        { id: 'c6-s-45', type: QuestionType.Single, question: '20 世纪40年代前期，中国共产党以延安为中心，在全党范围内开展了一场普遍的马克思主义思想教育运动，即（ ）。', options: ['A.整风运动', 'B.调查研究', 'C.知识分子思想改造运动', 'D.学习运动'], answer: ['A'] },
        { id: 'c6-s-46', type: QuestionType.Single, question: '（ ）将毛泽东思想规定为党的一切工作的指针。', options: ['A.中共六大', 'B.六届七中全会', 'C.中共七大', 'D.七届二中全会'], answer: ['C'] },
        { id: 'c6-s-47', type: QuestionType.Single, question: '1945 年 4 月，包括解放区代表( )在内的中国代表团出席了联合国制宪会议...', options: ['A.董必武', 'B.林伯渠', 'C.周恩来', 'D.王若飞'], answer: ['A'] },
        { id: 'c6-s-48', type: QuestionType.Single, question: '抗日民主政权十分重视根据地的经济建设，普遍实行( )政策。', options: ['A.没收地主土地', 'B.保存富农经济', 'C.减租减息', 'D.没收一切土地'], answer: ['C'] },
        { id: 'c6-s-49', type: QuestionType.Single, question: '1945 年（ ），日本代表在投降书上签字。至此，中国人民抗日战争胜利结束...', options: ['A.7 月26日', 'B.8 月14日', 'C.8 月15日', 'D.9月2日'], answer: ['D'] },
        { id: 'c6-s-50', type: QuestionType.Single, question: '（ ）是中国人民抗日战争胜利纪念日。', options: ['A.8 月15日', 'B.9 月2日', 'C.9 月18日', 'D.9月3日'], answer: ['D'] },
        { id: 'c6-s-51', type: QuestionType.Single, question: '1945 年 10 月25日，中国政府在（ ）举行受降仪式，成为抗日战争取得完全胜利的重要标志。', options: ['A.南京', 'B.广州', 'C.河内', 'D.台湾'], answer: ['D'] },
        { id: 'c6-s-52', type: QuestionType.Single, question: '最早为中国抗日战争提供援助的是（ ）。', options: ['A.苏联', 'B.英国', 'C.美国', 'D.法国'], answer: ['A'] },
        { id: 'c6-s-53', type: QuestionType.Single, question: '1945 年 4 月20日，中共扩大的（ ）通过了《关于若干历史问题的决议》...', options: ['A.六届六中全会', 'B.六届七中全会', 'C.七届一中全会', 'D.七届二中全会'], answer: ['B'] },
        { id: 'c6-s-54', type: QuestionType.Single, question: '为纪念在抢救八路军伤员时被感染，为中国人民解放事业献出生命的加拿大共产党员，毛泽东写下悼念文章（ ）。', options: ['A.《为人民服务》', 'B.《愚公移山》', 'C.《纪念白求恩》', 'D.《纪念张思德》'], answer: ['C'] },
        { id: 'c6-s-55', type: QuestionType.Single, question: '来华组建了美国援华志愿航空队的是（ ）。', options: ['A.陈纳德', 'B.库里申科', 'C.柯棣华', 'D.陈嘉庚'], answer: ['A'] },
        { id: 'c6-s-56', type: QuestionType.Single, question: '来华参加对日作战，并为帮助中国运送战略物资而冒险开辟驼峰航线的是（ ）。', options: ['A.美国援华志愿航空队', 'B.英国援华志愿航空队', 'C.法国空军志愿队', 'D.苏联空军志愿队'], answer: ['A'] },

        // 多选题 (27道)
        { id: 'c6-m-1', type: QuestionType.Multiple, question: '以下说法正确的有（ ）。', options: ['A.19 世纪60年代明治维新以后，日本开始走上资本主义道路', 'B.1927 年日本首相广田弘毅制定了《对华政策纲要》', 'C.日本军国主义势力推行对外扩张的“大陆政策”', 'D.日本成为亚洲的战争策源地'], answer: ['A', 'C', 'D'] },
        { id: 'c6-m-2', type: QuestionType.Multiple, question: '日本侵略者在其占领区...犯下了空前严重的罪行，包括（ ）。', options: ['A.制造惨绝人寰的大屠杀，残害中国人民', 'B.疯狂掠夺中国的资源与财富', 'C.强制推行奴化教育，肆意摧残中国文化', 'D.给中国造成巨大的直接和间接的经济损失'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c6-m-3', type: QuestionType.Multiple, question: '中国共产党直接领导了东北人民的抗日武装斗争，先后选派（ ）等人到东北。', options: ['A.杨靖宇', 'B.赵尚志', 'C.赵一曼', 'D.吉鸿昌'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-4', type: QuestionType.Multiple, question: '1933 年初，中国共产党领导的抗日游击队先后在东北各地崛起。其后又先后改编、改建为（ ）。', options: ['A.东北人民革命军', 'B.东北抗日联军', 'C.抗日义勇军', 'D.抗日同盟军'], answer: ['A', 'B'] },
        { id: 'c6-m-5', type: QuestionType.Multiple, question: '抗日战争是中华民族全民族的反侵略战争，中华儿女为民族独立和自由不惜抛头颅、洒热血，比如（ ）。', options: ['A.华北农妇邓玉芬把丈夫和5个孩子送上前线，他们全部战死沙场', 'B.民族工商业者踊跃为前线捐赠钱物', 'C.少数民族群众积极参加抗日战争', 'D.港澳同胞和海外华侨也以各种方式参加抗日活动'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c6-m-6', type: QuestionType.Multiple, question: '从卢沟桥事变，到1938年10月（ ）失守，中国抗战处于战略防御阶段。', options: ['A.南京', 'B.广州', 'C.武汉', 'D.长沙'], answer: ['B', 'C'] },
        { id: 'c6-m-7', type: QuestionType.Multiple, question: '中国抗战战略防御阶段，国民党军队组织了（ ）会战等一系列大战役。', options: ['A.淞沪', 'B.忻口', 'C.徐州', 'D.武汉'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c6-m-8', type: QuestionType.Multiple, question: '抗战期间（ ）分别由北平、天津迁往昆明，合并组建为国立西南联合大学。', options: ['A.北京大学', 'B.天津大学', 'C.清华大学', 'D.南开大学'], answer: ['A', 'C', 'D'] },
        { id: 'c6-m-9', type: QuestionType.Multiple, question: '抗日战争进入相持阶段后，日本对国民党政府采取( )的方针。', options: ['A.政治诱降为主', 'B.政治诱降为辅', 'C.军事打击为主', 'D.军事打击为辅'], answer: ['A', 'D'] },
        { id: 'c6-m-10', type: QuestionType.Multiple, question: '1939 年 1 月，国民党五届五中全会决定成立“防共委员会”，确定了“（ ）”的方针，标志着国民党政府逐步转变为消极抗战。', options: ['A.防共', 'B.限共', 'C.溶共', 'D.反共'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c6-m-11', type: QuestionType.Multiple, question: '毛泽东在《论持久战》中科学预测了抗日战争将经过（ ）。', options: ['A.战略防御阶段', 'B.战略相持阶段', 'C.战略反攻阶段', 'D.战略防守阶段'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-12', type: QuestionType.Multiple, question: '八路军配合国民党军队取得了（ ）等胜利。', options: ['A.平型关作战', 'B.雁门关伏击战', 'C.夜袭阳明堡日军机场', 'D.百团大战'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-13', type: QuestionType.Multiple, question: '在艰苦的敌后抗战中，涌现出无数可歌可泣的英雄事迹，包括（ ）等。', options: ['A.八女投江', 'B.狼牙山五壮士', 'C.刘老庄连', 'D.杨靖宇、赵尚志等'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c6-m-14', type: QuestionType.Multiple, question: '抗战相持阶段到来以后，国民党开始消极抗日、积极反攻，为此，1939年7月，中国共产党提出（ ）口号，继续争取同蒋介石集团合作抗日。', options: ['A.坚持抗战到底——反对中途妥协', 'B.巩固国内团结——反对内部分裂', 'C.发展中间势力，争取进步势力', 'D.力求全国进步——反对向后倒退'], answer: ['A', 'B', 'D'] },
        { id: 'c6-m-15', type: QuestionType.Multiple, question: '中国共产党提出巩固抗日民族统一战线的策略方针是( )。', options: ['A.发展进步势力', 'B.争取中间势力', 'C.孤立顽固势力', 'D.坚持独立自主'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-16', type: QuestionType.Multiple, question: '中国共产党在抗日民主根据地实行“三三制”原则，即( )各占1/3。', options: ['A.共产党员', 'B.非党的左派进步分子', 'C.国民党员', 'D.中间派'], answer: ['A', 'B', 'D'] },
        { id: 'c6-m-17', type: QuestionType.Multiple, question: '全民族抗战开始后，中共中央创办了一批学校，包括（ ）。', options: ['A.中国人民抗日军事政治大学', 'B.鲁迅艺术学院', 'C.延安自然科学院', 'D.西南联大'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-18', type: QuestionType.Multiple, question: '抗战期间，中国共产党的（ ）在国民党统治区公开发行，及时宣传党的主张，鼓舞和激励群众的抗战热情。', options: ['A.《新华日报》', 'B.《解放日报》', 'C.《群众》周刊', 'D.《解放》周刊'], answer: ['A', 'C'] },
        { id: 'c6-m-19', type: QuestionType.Multiple, question: '关于抗战时期文化工作的开展，说法正确的有（ ）。', options: ['A.在周恩来和郭沫若的参与和领导下，团聚了一批文化界爱国人士', 'B.在中国共产党推动和影响下，文化界各抗敌协会相继成立', 'C.武汉失守前后，一大批文化界人士迁移到天津、香港、南京等地', 'D.中共中央南方局设立文化工作委员会，具体领导大后方的进步文化工作'], answer: ['A', 'B', 'D'] },
        { id: 'c6-m-20', type: QuestionType.Multiple, question: '20 世纪30年代后期和40年代前期，为了将丰富的中国革命实际经验马克思主义化...毛泽东撰写了（ ）等一批重要的理论著作。', options: ['A.《<共产党人>发刊词》', 'B.《中国革命和中国共产党》', 'C.《新民主主义论》', 'D.《论人民民主专政》'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-21', type: QuestionType.Multiple, question: '毛泽东阐明了中国共产党在新民主主义革命阶段的基本纲领，经济上，（ ）。', options: ['A.推翻帝国主义和封建主义的压迫，建立新民主主义共和国', 'B.建立国营经济', 'C.没收地主阶级的土地归农民所有', 'D.允许民族资本主义经济的发展和富农经济的存在'], answer: ['B', 'C', 'D'] },
        { id: 'c6-m-22', type: QuestionType.Multiple, question: '中国共产党在新民主主义革命中战胜敌人的主要法宝有( )。', options: ['A.土地革命', 'B.统一战线', 'C.武装斗争', 'D.党的建设'], answer: ['B', 'C', 'D'] },
        { id: 'c6-m-23', type: QuestionType.Multiple, question: '抗日民族统一战线中的中间势力包括( )。', options: ['A.民族资产阶级', 'B.开明绅士', 'C.城市小资产阶级', 'D.地方实力派'], answer: ['A', 'B', 'D'] },
        { id: 'c6-m-24', type: QuestionType.Multiple, question: '关于中国抗战说法正确的有（ ）。', options: ['A.中国人民的抗日战争开展时间最早、持续时间最长', 'B.中国人民抗日战争的胜利是近代以来中国抗击外敌入侵的第一次完全胜利', 'C.中国人民的抗日战争为中华民族由近代以来陷入深重危机走向伟大复兴确立了历史转折点', 'D.以共产主义为核心的民族精神是中国人民抗日战争胜利的决定因素'], answer: ['A', 'B', 'C'] },
        { id: 'c6-m-25', type: QuestionType.Multiple, question: '抗日民主根据地是认真贯彻和实现中国共产党全面抗战路线、坚持抗战和争取胜利的阵地。中国共产党进行抗日民主根据地政权建设的主要举措有（ ）。', options: ['A.在少数民族聚居地区试行民族区域自治', 'B.各级抗日民主政权机构领导人通过人民选举产生', 'C.实行工农兵代表大会制度', 'D.抗日民主政府在工作人员分配上实行“三三制”原则'], answer: ['B', 'D'] },
        { id: 'c6-m-26', type: QuestionType.Multiple, question: '抗日战争是近代以来中华民族反抗外敌入侵第一次取得完全胜利的民族解放战争。中国赢得抗日战争胜利的主要原因有（ ）。', options: ['A.中国的国力空前强大', 'B.中国共产党的中流砥柱作用是关键', 'C.得到国际反法西斯力量的同情和支持', 'D.全民族抗战是法宝'], answer: ['B', 'C', 'D'] },
        { id: 'c6-m-27', type: QuestionType.Multiple, question: '中国人民抗日战争的胜利，促进了中华民族的大团结...中国人民向世界展示了（ ）。', options: ['A.天下兴亡、匹夫有责的爱国情怀', 'B.视死如归、宁死不屈的民族气节', 'C.不畏强暴、血战到底的英雄气概', 'D.百折不挠、坚韧不拔的必胜信念'], answer: ['A', 'B', 'C', 'D'] }
    ]
  },
  {
    id: 'ch7',
    title: '第七章 为建立新中国而奋斗',
    questions: [
        // 单选题 (20道)
        { id: 'c7-s-1', type: QuestionType.Single, question: '抗日战争胜利后，中国共产党的力量壮大起来，人民军队数量达到（ ）人，解放区扩大到（ ）人口。', options: ['A.132 万 1亿', 'B.10 万 3亿', 'C.270 万 0.5 亿', 'D.50万 4亿'], answer: ['A'] },
        { id: 'c7-s-2', type: QuestionType.Single, question: '1945 年 8月25日，中共中央发表《对目前时局的宣言》，明确提出（ ）的口号。', options: ['A “蒋反我亦反，蒋停我亦停”', 'B 稳定、统一', 'C “打倒蒋介石，解放全中国”', 'D 和平、民主、团结'], answer: ['D'] },
        { id: 'c7-s-3', type: QuestionType.Single, question: '1945 年 8 月14日、20日、23日，蒋介石三次电邀毛泽东到（ ）共商“国际国内各种重要问题”。', options: ['A.南京', 'B.重庆', 'C.上海', 'D.广州'], answer: ['B'] },
        { id: 'c7-s-4', type: QuestionType.Single, question: '1945 年 10 月10日，国共双方签署（ ），确认和平建国的基本方针。', options: ['A 《共同纲领》', 'B 《政府与中共代表会谈纪要》', 'C 《关于中国共产党与国民党的关系问题的决议》', 'D 《关于若干历史问题的决议》'], answer: ['B'] },
        { id: 'c7-s-5', type: QuestionType.Single, question: '（ ）年6月底，国民党军以进攻中原解放区为起点，挑起了全国性的内战。', options: ['A.1943', 'B.1944', 'C.1945', 'D.1946'], answer: ['D'] },
        { id: 'c7-s-6', type: QuestionType.Single, question: '1946 年 6月至1947年6月一年的时间里，人民军队处于（ ）阶段。', options: ['A.战略转移', 'B.战略防御', 'C.战略进攻', 'D.战略退却'], answer: ['B'] },
        { id: 'c7-s-7', type: QuestionType.Single, question: '1947 年 10 月10日，中国人民解放军总部发表宣言，提出（ ）的口号。', options: ['A.“打倒蒋介石，解放全中国”', 'B.“反对内战，争取自由”', 'C.“没有共产党，就没有新中国”', 'D.“保田参军”'], answer: ['A'] },
        { id: 'c7-s-8', type: QuestionType.Single, question: '1948 年 8月，国统区物价比1937年全民族抗战前暴涨了（ ）多倍。', options: ['A.47 万', 'B.102 万', 'C.540 万', 'D.725万'], answer: ['D'] },
        { id: 'c7-s-9', type: QuestionType.Single, question: '1945 年底，昆明学生发动了以“反对内战，争取自由”为主要口号的（ ）运动。', options: ['A 一二三〇运动', 'B 一二·一运动', 'C 抗暴运动', 'D 五二〇运动'], answer: ['B'] },
        { id: 'c7-s-10', type: QuestionType.Single, question: '（ ）年5月20日，南京、北平等地爆发了反饥饿、反内战运动。', options: ['A.1946', 'B.1947', 'C.1948', 'D.1949'], answer: ['B'] },
        { id: 'c7-s-11', type: QuestionType.Single, question: '1941 年 3 月，（ ）在重庆诞生。', options: ['A 中国国民党革命委员会', 'B 中国民主政团同盟', 'C 中国民主建国会', 'D 中国农工民主党'], answer: ['B'] },
        { id: 'c7-s-12', type: QuestionType.Single, question: '1945 年 12 月，中国民主促进会在（ ）宣告成立。', options: ['A 香港', 'B重庆', 'C上海', 'D 台湾'], answer: ['C'] },
        { id: 'c7-s-13', type: QuestionType.Single, question: '（ ）年1月22日，部分民主党派领导人和无党派人士55人联合发表《对时局的意见》。', options: ['A.1946', 'B.1947', 'C.1948', 'D.1949'], answer: ['D'] },
        { id: 'c7-s-14', type: QuestionType.Single, question: ' 1949 年6 月30日，毛泽东发表了（ ）一文，指出人民民主专政需要工人阶级的领导。', options: ['A．《论人民民主专政》', 'B．《论新阶段》', 'C．《中国革命战争的战略问题》', 'D．《论联合政府》'], answer: ['A'] },
        { id: 'c7-s-15', type: QuestionType.Single, question: '1949 年 9 月21日，中国人民政治协商会议第一届全体会议在（ ）开幕。', options: ['A．北京', 'B．北平', 'C．天津', 'D．南京'], answer: ['B'] },
        { id: 'c7-s-16', type: QuestionType.Single, question: '毛泽东告诫全党...提出“务必使同志们继续地保持谦虚、谨慎、不骄、不躁的作风，务必使同志们继续地保持艰苦奋斗的作风”，是在（ ）。', options: ['A．中共七大', 'B．中共七届二中全会', 'C．中共七届三中全会', 'D．中共八大'], answer: ['B'] },
        { id: 'c7-s-17', type: QuestionType.Single, question: '下列关于中国人民政治协商会议第一届全体会议的说法，不正确的是（ ）。', options: ['A．一致同意以新民主主义即人民民主主义为中华人民共和国的政治基础', 'B．通过了《中国人民政治协商会议共同纲领》', 'C．通过了中央人民政府组织法', 'D．制定了第一部正式宪法'], answer: ['D'] },
        { id: 'c7-s-18', type: QuestionType.Single, question: '抗战胜利后，中国社会的主要矛盾是（ ）。', options: ['A.共产党和国民党的矛盾', 'B.中国人民同美帝国主义支持的国民党反动派之间的矛盾', 'C.中华民族和外国资本主义的矛盾', 'D.中国人民同美帝国主义的矛盾'], answer: ['B'] },
        { id: 'c7-s-19', type: QuestionType.Single, question: '（ ）是中国共产党领导的以工农联盟为基础的人民民主统一战线的组织形式。', options: ['A 《共同纲领》', 'B.全国代表大会制度', 'C.人民政协', 'D 平等协商'], answer: ['C'] },
        { id: 'c7-s-20', type: QuestionType.Single, question: '人民政协会议的召开，标志着中国的新型（ ）制度的确立。', options: ['A.国家', 'B.民族', 'C.民主', 'D.政党'], answer: ['D'] },

        // 多选题 (16道)
        { id: 'c7-m-1', type: QuestionType.Multiple, question: '1946 年 1月10日，政治协商会议在重庆开幕，会议达成的协议主要包括（ ）。', options: ['A 政府组织案', 'B 国民大会案', 'C 和平建国纲领', 'D 军事问题案和宪法草案案'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c7-m-2', type: QuestionType.Multiple, question: '从1947 年3月至6月，解放军经过4个月的内线作战，努力打退国民党军的重点进攻，并在（ ）等地开始局部反攻。', options: ['A．东北', 'B．热河', 'C．冀东', 'D．豫南'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c7-m-3', type: QuestionType.Multiple, question: '1947 年 6月底，根据中共中央的决策和部署，（ ）与（ ）率领的晋冀鲁豫野战军主力，实施中央突破，千里跃进大别山。', options: ['A．刘伯承', 'B．邓小平', 'C．陈毅', 'D．粟裕'], answer: ['A', 'B'] },
        { id: 'c7-m-4', type: QuestionType.Multiple, question: '1949 年 4月21日，毛泽东、朱德发布《向全国进军的命令》。人民解放军（ ）野战军在东起江阴，西至湖口的战线上强渡长江。', options: ['A．第一', 'B．第二', 'C．第三', 'D．第四'], answer: ['B', 'C'] },
        { id: 'c7-m-5', type: QuestionType.Multiple, question: '1949 年 3月召开的中共七届二中全会做出（ ）等有关规定。', options: ['A 中国不宜实行联邦制', 'B 不要把中国同志和马克思、恩格斯、列宁、斯大林并列', 'C 不用党的领导者的名字作地名、街名和企业的名字', 'D 不给党的领导者祝寿，不送礼，少敬酒，少拍掌'], answer: ['B', 'C', 'D'] },
        { id: 'c7-m-6', type: QuestionType.Multiple, question: '1949 年 9 月21日召开的中国人民政治协商会议第一届全体会议选举了（ ）人为中央人民政府副主席。', options: ['A．朱德和刘少奇', 'B．宋庆龄和李济深', 'C．张澜和高岗', 'D．毛泽东和周恩来'], answer: ['A', 'B', 'C'] },
        { id: 'c7-m-7', type: QuestionType.Multiple, question: '1946 年 1月10日，政治协商会议在重庆开幕，出席会议的有（ ）的代表共38人。', options: ['A 国民党', 'B 共产党', 'C 民主同盟', 'D 青年党和无党派人士'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c7-m-8', type: QuestionType.Multiple, question: '全面内战爆发时，中国共产党面临的形势极为严峻，表现在：', options: ['A 国民党政府拥有总兵力约430万人，控制着全国76%的面积', 'B 国民党政府控制着约3.39亿人口', 'C 美国为国民党政府训练、装备了50万军队', 'D 解放区是被分割、包围的'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c7-m-9', type: QuestionType.Multiple, question: '解放战争时期，在国民党统治区形成了以学生运动为先导的人民民主运动，成为配合人民解放战争的第二条战线。第二条战线形成的原因有（ ）。', options: ['A 国民党政府专制独裁、官员贪污腐败', 'B 城市失业人数陡增，工农业生产严重萎缩', 'C 国民党顽固坚持内战政策', 'D 恶性通货膨胀'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c7-m-10', type: QuestionType.Multiple, question: '1948 年8 月至1949年9月，中共中央香港分局和香港工委组织护送北上的民主人士北上达20多次，其中包括（ ）等', options: ['A 沈钧儒和李济深', 'B 张澜和黄炎培', 'C 罗隆基', 'D 章伯钧'], answer: ['A', 'B', 'C', 'D'] },
        { id: 'c7-m-11', type: QuestionType.Multiple, question: '人民解放战争进入夺取全国胜利的决定性阶段后，中国人民解放军先后发动了（ ）三大战役。', options: ['A 辽沈战役', 'B 济南战役', 'C 淮海战役', 'D 平津战役'], answer: ['A', 'C', 'D'] },
        { id: 'c7-m-12', type: QuestionType.Multiple, question: '1947 年 3 月，国民党当局限令中共驻（ ）代表及工作人员全部撤退，国共关系彻底破裂。', options: ['A 南京', 'B 上海', 'C 重庆', 'D 北平'], answer: ['A', 'B', 'C'] },
        { id: 'c7-m-13', type: QuestionType.Multiple, question: '抗战胜利初期，中国共产党考虑对国民党开展哪些活动？', options: ['A.进行谈判', 'B.避免内战', 'C.实现和平建国', 'D.战略决战'], answer: ['A', 'B', 'C'] },
        { id: 'c7-m-14', type: QuestionType.Multiple, question: '下列关于重庆谈判和政治协商会议的表述中，正确的是（ ）。', options: ['A.为了争取和平民主，毛泽东不顾个人安危赴重庆谈判', 'B.周恩来、刘少奇、王若飞也飞赴重庆参加了谈判', 'C.增进了各界群众对共产党的了解', 'D.共产党通过谈判团结和教育了广大人民'], answer: ['A', 'C', 'D'] }, // Note: Liu Shaoqi did NOT go to Chongqing. Zhou Enlai and Wang Ruofei did. So B is wrong. Correct: A, C, D.
        { id: 'c7-m-15', type: QuestionType.Multiple, question: '国民党军被迫放弃对解放区的全面进攻后，改为对下列哪些解放区进行重点进攻（ ）', options: ['A.陕北', 'B.山东', 'C.山西', 'D.河南'], answer: ['A', 'B'] },
        { id: 'c7-m-16', type: QuestionType.Multiple, question: '关于土改运动表述正确的有：', options: ['A 一度发生过侵犯部分中农利益的“左”的错误', 'B 有助于人民解放战争获得人力、物力支援', 'C 绝大多数农民自觉地在中国共产党周围团结起来', 'D 广大农民的政治觉悟和组织程度'], answer: ['A', 'B', 'C', 'D'] }
    ]
  }
];
